#!/usr/bin/env python3
"""
Carica tutti i comuni italiani con le aliquote addizionale comunale IRPEF 2025
nella tabella addizionali_irpef del database gestptf.

Elimina tutte le voci 'comunale' esistenti e le reinserisce.
NON tocca le voci 'regionale'.
"""

import sys
import os

# Add parent dir to path so we can import database module
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from database import get_db

# ============================================================================
# Dizionario completo comuni italiani per regione
# Formato: { "Regione": [ ("Nome Comune", aliquota), ... ] }
# Aliquote espresse in percentuale (es. 0.8 = 0.8%)
# Fonti: Ministero dell'Economia - Dipartimento delle Finanze, anno 2025
# ============================================================================

COMUNI_PER_REGIONE = {

    # ========================================================================
    # LOMBARDIA
    # ========================================================================
    "Lombardia": [
        ("Milano", 0.8), ("Brescia", 0.8), ("Bergamo", 0.8), ("Monza", 0.6),
        ("Varese", 0.8), ("Como", 0.8), ("Pavia", 0.8), ("Cremona", 0.8),
        ("Mantova", 0.8), ("Lecco", 0.8), ("Lodi", 0.8), ("Sondrio", 0.6),
        ("Busto Arsizio", 0.8), ("Sesto San Giovanni", 0.8),
        ("Cinisello Balsamo", 0.8), ("Legnano", 0.8), ("Gallarate", 0.8),
        ("Rho", 0.8), ("Vigevano", 0.7), ("Desio", 0.8), ("Seregno", 0.6),
        ("Cologno Monzese", 0.8), ("Paderno Dugnano", 0.8),
        ("Pioltello", 0.8), ("Corsico", 0.8), ("Bollate", 0.8),
        ("Rozzano", 0.8), ("Abbiategrasso", 0.8), ("Crema", 0.8),
        ("San Donato Milanese", 0.8), ("San Giuliano Milanese", 0.8),
        ("Cernusco sul Naviglio", 0.8), ("Saronno", 0.8), ("Cantù", 0.8),
        ("Erba", 0.7), ("Mariano Comense", 0.7), ("Limbiate", 0.8),
        ("Cesano Maderno", 0.8), ("Lissone", 0.8), ("Meda", 0.8),
        ("Giussano", 0.8), ("Brugherio", 0.8), ("Nova Milanese", 0.8),
        ("Carate Brianza", 0.8), ("Vimercate", 0.8), ("Segrate", 0.8),
        ("Opera", 0.8), ("Melzo", 0.8), ("Gorgonzola", 0.8),
        ("Cassano d'Adda", 0.8), ("Treviglio", 0.8), ("Dalmine", 0.8),
        ("Seriate", 0.8), ("Romano di Lombardia", 0.8),
        ("Caravaggio", 0.8), ("Stezzano", 0.8), ("Albino", 0.8),
        ("Nembro", 0.8), ("Alzano Lombardo", 0.8), ("Sarnico", 0.7),
        ("Trescore Balneario", 0.8), ("Lovere", 0.7), ("Clusone", 0.7),
        ("Palazzolo sull'Oglio", 0.8), ("Chiari", 0.8), ("Lumezzane", 0.8),
        ("Desenzano del Garda", 0.8), ("Montichiari", 0.8),
        ("Darfo Boario Terme", 0.8), ("Rovato", 0.8), ("Orzinuovi", 0.8),
        ("Castiglione delle Stiviere", 0.8), ("Suzzara", 0.8),
        ("Viadana", 0.8), ("Casalmaggiore", 0.8), ("Codogno", 0.8),
        ("Casalpusterlengo", 0.8), ("Voghera", 0.8), ("Mortara", 0.7),
        ("Stradella", 0.7), ("Broni", 0.7), ("Mede", 0.7),
        ("Legnano", 0.8), ("Magenta", 0.8), ("Parabiago", 0.8),
        ("Lainate", 0.8), ("Arese", 0.8), ("Garbagnate Milanese", 0.8),
        ("Senago", 0.8), ("Bresso", 0.8), ("Cusano Milanino", 0.8),
        ("Cinisello Balsamo", 0.8), ("Muggiò", 0.8), ("Villasanta", 0.7),
        ("Arcore", 0.7), ("Concorezzo", 0.8), ("Agrate Brianza", 0.8),
        ("Bernareggio", 0.7), ("Carnate", 0.7), ("Usmate Velate", 0.7),
        ("Trezzo sull'Adda", 0.8), ("Inzago", 0.8), ("Cassina de' Pecchi", 0.8),
        ("Cologno Monzese", 0.8), ("Vimodrone", 0.8), ("Buccinasco", 0.8),
        ("Assago", 0.8), ("Cesano Boscone", 0.8), ("Trezzano sul Naviglio", 0.8),
        ("Gaggiano", 0.7), ("Binasco", 0.8), ("Lacchiarella", 0.7),
        ("Peschiera Borromeo", 0.8), ("Pantigliate", 0.8), ("Paullo", 0.8),
        ("Locate di Triulzi", 0.8), ("San Zenone al Lambro", 0.7),
        ("Melegnano", 0.8), ("Cerro Maggiore", 0.8), ("Rescaldina", 0.8),
        ("Castellanza", 0.8), ("Olgiate Olona", 0.8), ("Solbiate Olona", 0.8),
        ("Fagnano Olona", 0.8), ("Gorla Minore", 0.8), ("Marnate", 0.8),
        ("Tradate", 0.8), ("Caronno Pertusella", 0.8), ("Gerenzano", 0.8),
        ("Uboldo", 0.8), ("Origgio", 0.8), ("Solaro", 0.8),
        ("Ceriano Laghetto", 0.8), ("Cogliate", 0.8), ("Lentate sul Seveso", 0.8),
        ("Barlassina", 0.8), ("Seveso", 0.8), ("Cesano Maderno", 0.8),
        ("Bovisio-Masciago", 0.8), ("Varedo", 0.8), ("Macherio", 0.7),
        ("Sovico", 0.7), ("Biassono", 0.7), ("Vedano al Lambro", 0.7),
        ("Lazzate", 0.8), ("Misinto", 0.8), ("Cermenate", 0.7),
        ("Lomazzo", 0.7), ("Turate", 0.7), ("Cadorago", 0.7),
        ("Fino Mornasco", 0.7), ("Lurate Caccivio", 0.7),
        ("Olgiate Comasco", 0.7), ("Appiano Gentile", 0.7),
        ("Inverigo", 0.7), ("Lurago d'Erba", 0.7), ("Merone", 0.7),
        ("Calolziocorte", 0.8), ("Merate", 0.8), ("Oggiono", 0.8),
        ("Mandello del Lario", 0.7), ("Bellano", 0.7), ("Colico", 0.7),
        ("Casatenovo", 0.8), ("Missaglia", 0.7), ("Imbersago", 0.7),
        ("Brivio", 0.7), ("Osnago", 0.7),
        ("San Colombano al Lambro", 0.8), ("Tavazzano con Villavesco", 0.8),
        ("Somma Lombardo", 0.8), ("Sesto Calende", 0.8),
        ("Angera", 0.7), ("Ispra", 0.7), ("Laveno-Mombello", 0.7),
        ("Luino", 0.8), ("Gavirate", 0.7), ("Cittiglio", 0.7),
        ("Besozzo", 0.7), ("Cocquio-Trevisago", 0.7),
        ("Malnate", 0.8), ("Induno Olona", 0.7), ("Arcisate", 0.7),
        ("Bisuschio", 0.7), ("Porto Ceresio", 0.7), ("Marchirolo", 0.7),
        ("Cunardo", 0.7), ("Cuveglio", 0.7), ("Cuvio", 0.7),
        ("Ponte San Pietro", 0.8), ("Curno", 0.8), ("Mozzo", 0.8),
        ("Villa d'Almè", 0.7), ("Zogno", 0.7), ("San Pellegrino Terme", 0.7),
        ("Piazza Brembana", 0.6), ("San Giovanni Bianco", 0.7),
        ("Sotto il Monte Giovanni XXIII", 0.7), ("Calusco d'Adda", 0.8),
        ("Osio Sotto", 0.8), ("Bonate Sotto", 0.8), ("Mapello", 0.8),
        ("Ciserano", 0.8), ("Verdello", 0.8), ("Spirano", 0.8),
        ("Grassobbio", 0.8), ("Orio al Serio", 0.8), ("Azzano San Paolo", 0.8),
        ("Curtatone", 0.8), ("Porto Mantovano", 0.8), ("Virgilio", 0.8),
        ("San Giorgio di Mantova", 0.8), ("Gonzaga", 0.8),
        ("Ostiglia", 0.8), ("Pegognaga", 0.8), ("Quistello", 0.8),
    ],

    # ========================================================================
    # PIEMONTE
    # ========================================================================
    "Piemonte": [
        ("Torino", 0.8), ("Novara", 0.8), ("Alessandria", 0.8),
        ("Asti", 0.8), ("Cuneo", 0.6), ("Vercelli", 0.8),
        ("Biella", 0.8), ("Verbania", 0.6), ("Moncalieri", 0.8),
        ("Collegno", 0.8), ("Rivoli", 0.8), ("Nichelino", 0.8),
        ("Settimo Torinese", 0.8), ("Grugliasco", 0.8), ("Chieri", 0.8),
        ("Pinerolo", 0.8), ("Venaria Reale", 0.8), ("Chivasso", 0.8),
        ("Ivrea", 0.8), ("Casale Monferrato", 0.8), ("Orbassano", 0.8),
        ("Rivalta di Torino", 0.8), ("Beinasco", 0.8), ("Carmagnola", 0.8),
        ("Borgomanero", 0.8), ("Arona", 0.7), ("Trecate", 0.8),
        ("Galliate", 0.8), ("Oleggio", 0.8), ("Castelletto sopra Ticino", 0.7),
        ("Borgosesia", 0.8), ("Gattinara", 0.8), ("Santhià", 0.8),
        ("Crescentino", 0.8), ("Trino", 0.8), ("Livorno Ferraris", 0.8),
        ("Cossato", 0.8), ("Valdilana", 0.8), ("Trivero", 0.8),
        ("Vigliano Biellese", 0.8), ("Candelo", 0.7),
        ("Alba", 0.7), ("Bra", 0.7), ("Fossano", 0.7),
        ("Savigliano", 0.7), ("Mondovì", 0.7), ("Saluzzo", 0.7),
        ("Racconigi", 0.7), ("Busca", 0.6), ("Dronero", 0.6),
        ("Ceva", 0.7), ("Cherasco", 0.7), ("Sommariva del Bosco", 0.7),
        ("Tortona", 0.8), ("Novi Ligure", 0.8), ("Valenza", 0.8),
        ("Acqui Terme", 0.8), ("Ovada", 0.8), ("Serravalle Scrivia", 0.8),
        ("Nizza Monferrato", 0.8), ("Canelli", 0.8), ("Villanova d'Asti", 0.8),
        ("San Damiano d'Asti", 0.8), ("Costigliole d'Asti", 0.8),
        ("Domodossola", 0.7), ("Omegna", 0.7), ("Stresa", 0.6),
        ("Baveno", 0.6), ("Gravellona Toce", 0.7), ("Villadossola", 0.7),
        ("Leini", 0.8), ("Volpiano", 0.8), ("San Mauro Torinese", 0.8),
        ("Brandizzo", 0.8), ("Gassino Torinese", 0.8),
        ("Piossasco", 0.8), ("Giaveno", 0.8), ("Avigliana", 0.8),
        ("Alpignano", 0.8), ("Druento", 0.8), ("Pianezza", 0.8),
        ("San Maurizio Canavese", 0.8), ("Ciriè", 0.8), ("Lanzo Torinese", 0.8),
        ("Rivarolo Canavese", 0.8), ("Castellamonte", 0.8),
        ("Cuorgnè", 0.8), ("Pont Canavese", 0.8),
        ("Trofarello", 0.8), ("Cambiano", 0.8), ("Santena", 0.8),
        ("Vinovo", 0.8), ("Candiolo", 0.8), ("None", 0.8),
        ("Poirino", 0.8), ("Carignano", 0.8),
        ("Borgaro Torinese", 0.8), ("Caselle Torinese", 0.8),
        ("Mappano", 0.8), ("Leinì", 0.8),
        ("Tortona", 0.8), ("Castelnuovo Scrivia", 0.8),
        ("Sale", 0.8), ("Pontecurone", 0.8),
        ("Vigone", 0.7), ("Cavour", 0.7), ("Villafranca Piemonte", 0.7),
    ],

    # ========================================================================
    # VENETO
    # ========================================================================
    "Veneto": [
        ("Venezia", 0.8), ("Verona", 0.8), ("Padova", 0.8),
        ("Vicenza", 0.8), ("Treviso", 0.7), ("Rovigo", 0.8),
        ("Belluno", 0.5), ("Chioggia", 0.8), ("Mestre", 0.8),
        ("San Donà di Piave", 0.8), ("Jesolo", 0.7), ("Mira", 0.8),
        ("Mirano", 0.8), ("Spinea", 0.8), ("Martellago", 0.8),
        ("Noale", 0.7), ("Portogruaro", 0.8), ("Caorle", 0.7),
        ("Concordia Sagittaria", 0.8), ("Fossalta di Piave", 0.8),
        ("Dolo", 0.8), ("Stra", 0.8), ("Vigonza", 0.8),
        ("Albignasego", 0.8), ("Selvazzano Dentro", 0.8),
        ("Abano Terme", 0.8), ("Rubano", 0.8), ("Cadoneghe", 0.8),
        ("Limena", 0.8), ("Noventa Padovana", 0.8), ("Ponte San Nicolò", 0.8),
        ("Piove di Sacco", 0.8), ("Camposampiero", 0.8),
        ("Cittadella", 0.7), ("Camposampiero", 0.8), ("Monselice", 0.8),
        ("Este", 0.8), ("Montagnana", 0.8), ("Conselve", 0.8),
        ("Legnaro", 0.8), ("Padova", 0.8), ("Villafranca di Verona", 0.8),
        ("San Bonifacio", 0.8), ("Legnago", 0.8), ("Bussolengo", 0.8),
        ("Negrar di Valpolicella", 0.7), ("San Giovanni Lupatoto", 0.8),
        ("Grezzana", 0.7), ("San Pietro in Cariano", 0.7),
        ("Sommacampagna", 0.8), ("Sona", 0.7), ("Pescantina", 0.7),
        ("Zevio", 0.8), ("Cerea", 0.8), ("Bovolone", 0.8),
        ("Isola della Scala", 0.8), ("Vigasio", 0.8), ("Oppeano", 0.8),
        ("San Martino Buon Albergo", 0.8), ("Colognola ai Colli", 0.8),
        ("Caldiero", 0.7), ("Soave", 0.7), ("Monteforte d'Alpone", 0.8),
        ("Illasi", 0.7), ("Tregnago", 0.7),
        ("Bassano del Grappa", 0.8), ("Schio", 0.8), ("Thiene", 0.8),
        ("Valdagno", 0.8), ("Arzignano", 0.8), ("Chiampo", 0.8),
        ("Montecchio Maggiore", 0.8), ("Lonigo", 0.8),
        ("Noventa Vicentina", 0.8), ("Dueville", 0.8), ("Marostica", 0.7),
        ("Rosà", 0.7), ("Cassola", 0.7), ("Sandrigo", 0.7),
        ("Breganze", 0.7), ("Malo", 0.7), ("Isola Vicentina", 0.7),
        ("Torri di Quartesolo", 0.8), ("Altavilla Vicentina", 0.8),
        ("Creazzo", 0.8), ("Sovizzo", 0.8), ("Costabissara", 0.7),
        ("Montegalda", 0.7), ("Camisano Vicentino", 0.8),
        ("Grisignano di Zocco", 0.8),
        ("Conegliano", 0.8), ("Castelfranco Veneto", 0.8),
        ("Montebelluna", 0.7), ("Mogliano Veneto", 0.8),
        ("Vittorio Veneto", 0.7), ("Oderzo", 0.8), ("Casier", 0.7),
        ("Paese", 0.7), ("Roncade", 0.7), ("Preganziol", 0.8),
        ("Villorba", 0.7), ("Ponzano Veneto", 0.7), ("Silea", 0.7),
        ("Carbonera", 0.7), ("Spresiano", 0.7), ("Pieve di Soligo", 0.7),
        ("Valdobbiadene", 0.6), ("Asolo", 0.7), ("Riese Pio X", 0.7),
        ("Vedelago", 0.7), ("Istrana", 0.7), ("Loria", 0.7),
        ("Feltre", 0.6), ("Sedico", 0.5), ("Santa Giustina", 0.5),
        ("Ponte nelle Alpi", 0.5), ("Limana", 0.5), ("Mel", 0.5),
        ("Agordo", 0.5), ("Pieve di Cadore", 0.5), ("Cortina d'Ampezzo", 0.4),
        ("Adria", 0.8), ("Badia Polesine", 0.8), ("Lendinara", 0.8),
        ("Porto Viro", 0.8), ("Taglio di Po", 0.8), ("Occhiobello", 0.8),
        ("Fiesso Umbertiano", 0.8), ("Villadose", 0.8),
    ],

    # ========================================================================
    # EMILIA-ROMAGNA
    # ========================================================================
    "Emilia-Romagna": [
        ("Bologna", 0.8), ("Modena", 0.7), ("Parma", 0.7),
        ("Reggio Emilia", 0.8), ("Ravenna", 0.8), ("Ferrara", 0.8),
        ("Forlì", 0.8), ("Rimini", 0.8), ("Piacenza", 0.8),
        ("Cesena", 0.8), ("Imola", 0.8), ("Carpi", 0.7),
        ("Faenza", 0.8), ("Lugo", 0.8), ("Casalecchio di Reno", 0.8),
        ("San Lazzaro di Savena", 0.8), ("Formigine", 0.7),
        ("Sassuolo", 0.7), ("Scandiano", 0.8), ("Correggio", 0.8),
        ("Castelfranco Emilia", 0.7), ("Vignola", 0.7), ("Mirandola", 0.7),
        ("Cento", 0.8), ("Comacchio", 0.8), ("Argenta", 0.8),
        ("Codigoro", 0.8), ("Bondeno", 0.8), ("Copparo", 0.8),
        ("Fidenza", 0.7), ("Salsomaggiore Terme", 0.7),
        ("Borgotaro", 0.7), ("Collecchio", 0.7), ("Langhirano", 0.7),
        ("Noceto", 0.7), ("Medesano", 0.7), ("Sorbolo Mezzani", 0.7),
        ("Felino", 0.7), ("Traversetolo", 0.7),
        ("Fiorenzuola d'Arda", 0.8), ("Castel San Giovanni", 0.8),
        ("Rottofreno", 0.8), ("Podenzano", 0.8), ("Pontenure", 0.8),
        ("Cadeo", 0.8), ("Carpaneto Piacentino", 0.8),
        ("Guastalla", 0.8), ("Montecchio Emilia", 0.8),
        ("Rubiera", 0.8), ("Casalgrande", 0.8), ("Castellarano", 0.8),
        ("Castelnovo ne' Monti", 0.8), ("Sant'Ilario d'Enza", 0.8),
        ("Cavriago", 0.8), ("Bibbiano", 0.8), ("Brescello", 0.8),
        ("Novellara", 0.8), ("Rio Saliceto", 0.8), ("Campagnola Emilia", 0.8),
        ("Pavullo nel Frignano", 0.7), ("Maranello", 0.7),
        ("Fiorano Modenese", 0.7), ("Spilamberto", 0.7),
        ("Nonantola", 0.7), ("Bomporto", 0.7), ("Ravarino", 0.7),
        ("Soliera", 0.7), ("Novi di Modena", 0.7), ("Campogalliano", 0.7),
        ("San Cesario sul Panaro", 0.7), ("Savignano sul Panaro", 0.7),
        ("Castelnuovo Rangone", 0.7), ("Montese", 0.7),
        ("Cervia", 0.8), ("Alfonsine", 0.8), ("Russi", 0.8),
        ("Bagnacavallo", 0.8), ("Cotignola", 0.8), ("Conselice", 0.8),
        ("Massa Lombarda", 0.8), ("Fusignano", 0.8), ("Solarolo", 0.8),
        ("Forlimpopoli", 0.8), ("Bertinoro", 0.8), ("Meldola", 0.8),
        ("Predappio", 0.8), ("Modigliana", 0.8), ("Castrocaro Terme", 0.8),
        ("Savignano sul Rubicone", 0.8), ("Gambettola", 0.8),
        ("Gatteo", 0.8), ("San Mauro Pascoli", 0.8), ("Longiano", 0.8),
        ("Cesenatico", 0.8), ("Bellaria-Igea Marina", 0.8),
        ("Riccione", 0.8), ("Cattolica", 0.8), ("Misano Adriatico", 0.8),
        ("San Giovanni in Marignano", 0.8), ("Coriano", 0.8),
        ("Santarcangelo di Romagna", 0.8), ("Verucchio", 0.8),
        ("San Clemente", 0.8), ("Morciano di Romagna", 0.8),
        ("Budrio", 0.8), ("Minerbio", 0.8), ("Granarolo dell'Emilia", 0.8),
        ("Medicina", 0.8), ("Molinella", 0.8), ("Baricella", 0.8),
        ("San Giorgio di Piano", 0.8), ("San Pietro in Casale", 0.8),
        ("Crevalcore", 0.8), ("San Giovanni in Persiceto", 0.8),
        ("Anzola dell'Emilia", 0.8), ("Calderara di Reno", 0.8),
        ("Zola Predosa", 0.8), ("Pianoro", 0.8), ("Sasso Marconi", 0.8),
        ("Castel Maggiore", 0.8), ("Argelato", 0.8),
        ("Castelvetro di Modena", 0.7), ("Finale Emilia", 0.7),
        ("Concordia sulla Secchia", 0.7), ("San Possidonio", 0.7),
        ("San Felice sul Panaro", 0.7), ("Medolla", 0.7),
    ],

    # ========================================================================
    # TOSCANA
    # ========================================================================
    "Toscana": [
        ("Firenze", 0.8), ("Prato", 0.8), ("Livorno", 0.8),
        ("Arezzo", 0.8), ("Pisa", 0.8), ("Pistoia", 0.8),
        ("Lucca", 0.8), ("Siena", 0.6), ("Grosseto", 0.7),
        ("Massa", 0.8), ("Carrara", 0.8), ("Viareggio", 0.8),
        ("Empoli", 0.8), ("Scandicci", 0.8), ("Sesto Fiorentino", 0.8),
        ("Campi Bisenzio", 0.8), ("Bagno a Ripoli", 0.8),
        ("Calenzano", 0.8), ("Signa", 0.8), ("Lastra a Signa", 0.8),
        ("Pontassieve", 0.8), ("Figline e Incisa Valdarno", 0.8),
        ("San Casciano in Val di Pesa", 0.7), ("Greve in Chianti", 0.7),
        ("Reggello", 0.8), ("Rufina", 0.8), ("Borgo San Lorenzo", 0.8),
        ("Vicchio", 0.8), ("Scarperia e San Piero", 0.8),
        ("Barberino di Mugello", 0.8), ("Fucecchio", 0.8),
        ("Montecatini Terme", 0.8), ("Pescia", 0.8), ("Quarrata", 0.8),
        ("Monsummano Terme", 0.8), ("Agliana", 0.8), ("Montale", 0.8),
        ("Serravalle Pistoiese", 0.8), ("San Marcello Piteglio", 0.7),
        ("Capannori", 0.8), ("Altopascio", 0.8), ("Porcari", 0.8),
        ("Montecarlo", 0.8), ("Castelnuovo di Garfagnana", 0.7),
        ("Barga", 0.7), ("Bagni di Lucca", 0.7), ("Pietrasanta", 0.8),
        ("Camaiore", 0.8), ("Massarosa", 0.8), ("Forte dei Marmi", 0.8),
        ("Seravezza", 0.8), ("Stazzema", 0.7),
        ("Piombino", 0.8), ("Rosignano Marittimo", 0.8),
        ("Cecina", 0.8), ("Collesalvetti", 0.8), ("Portoferraio", 0.7),
        ("San Vincenzo", 0.8), ("Campiglia Marittima", 0.8),
        ("Cascina", 0.8), ("San Giuliano Terme", 0.8), ("Pontedera", 0.8),
        ("San Miniato", 0.8), ("Santa Croce sull'Arno", 0.8),
        ("Castelfranco di Sotto", 0.8), ("Volterra", 0.7),
        ("Pomarance", 0.7), ("Peccioli", 0.7), ("Calcinaia", 0.8),
        ("Bientina", 0.8), ("Vicopisano", 0.8), ("Ponsacco", 0.8),
        ("Lari", 0.8), ("Montopoli in Val d'Arno", 0.8),
        ("Cortona", 0.8), ("Sansepolcro", 0.8), ("Montevarchi", 0.8),
        ("San Giovanni Valdarno", 0.8), ("Terranuova Bracciolini", 0.8),
        ("Bibbiena", 0.8), ("Castiglion Fiorentino", 0.8),
        ("Foiano della Chiana", 0.8), ("Loro Ciuffenna", 0.8),
        ("Bucine", 0.8), ("Laterina Pergine Valdarno", 0.8),
        ("Poggibonsi", 0.8), ("Colle di Val d'Elsa", 0.8),
        ("Montepulciano", 0.7), ("Chiusi", 0.7), ("Sinalunga", 0.7),
        ("Montalcino", 0.6), ("Rapolano Terme", 0.7),
        ("Castelnuovo Berardenga", 0.7), ("Monteroni d'Arbia", 0.7),
        ("Asciano", 0.7), ("Sovicille", 0.7), ("San Gimignano", 0.6),
        ("Certaldo", 0.8), ("Castelfiorentino", 0.8),
        ("Montemurlo", 0.8), ("Poggio a Caiano", 0.8), ("Vaiano", 0.8),
        ("Vernio", 0.8), ("Carmignano", 0.8),
        ("Orbetello", 0.7), ("Follonica", 0.7), ("Castiglione della Pescaia", 0.7),
        ("Roccastrada", 0.7), ("Massa Marittima", 0.7),
        ("Monte Argentario", 0.7), ("Manciano", 0.7), ("Scarlino", 0.7),
        ("Aulla", 0.8), ("Pontremoli", 0.7), ("Fivizzano", 0.7),
        ("Montignoso", 0.8),
    ],

    # ========================================================================
    # LAZIO
    # ========================================================================
    "Lazio": [
        ("Roma", 0.9), ("Latina", 0.8), ("Frosinone", 0.8),
        ("Viterbo", 0.8), ("Rieti", 0.7), ("Fiumicino", 0.8),
        ("Guidonia Montecelio", 0.8), ("Tivoli", 0.8), ("Pomezia", 0.8),
        ("Anzio", 0.8), ("Nettuno", 0.8), ("Velletri", 0.8),
        ("Ardea", 0.8), ("Civitavecchia", 0.8), ("Ciampino", 0.8),
        ("Aprilia", 0.8), ("Formia", 0.8), ("Terracina", 0.8),
        ("Fondi", 0.8), ("Gaeta", 0.8), ("Cisterna di Latina", 0.8),
        ("Sezze", 0.8), ("Cori", 0.8), ("Priverno", 0.8),
        ("Pontinia", 0.8), ("Sabaudia", 0.8), ("San Felice Circeo", 0.7),
        ("Minturno", 0.8), ("Itri", 0.8), ("Sperlonga", 0.7),
        ("Cassino", 0.8), ("Sora", 0.8), ("Alatri", 0.8),
        ("Anagni", 0.8), ("Ferentino", 0.8), ("Isola del Liri", 0.8),
        ("Veroli", 0.8), ("Ceccano", 0.8), ("Monte San Giovanni Campano", 0.8),
        ("Boville Ernica", 0.8), ("Fiuggi", 0.8), ("Piedimonte San Germano", 0.8),
        ("Aquino", 0.8), ("Pontecorvo", 0.8), ("Roccasecca", 0.8),
        ("Arpino", 0.8), ("Ceprano", 0.8),
        ("Monterotondo", 0.8), ("Mentana", 0.8), ("Fonte Nuova", 0.8),
        ("Colleferro", 0.8), ("Valmontone", 0.8), ("Palestrina", 0.8),
        ("Zagarolo", 0.8), ("Cave", 0.8), ("Genazzano", 0.8),
        ("Artena", 0.8), ("Lariano", 0.8),
        ("Cerveteri", 0.8), ("Ladispoli", 0.8), ("Santa Marinella", 0.8),
        ("Bracciano", 0.8), ("Anguillara Sabazia", 0.8),
        ("Trevignano Romano", 0.7), ("Campagnano di Roma", 0.8),
        ("Formello", 0.8), ("Sacrofano", 0.8),
        ("Albano Laziale", 0.8), ("Marino", 0.8), ("Genzano di Roma", 0.8),
        ("Ariccia", 0.8), ("Castel Gandolfo", 0.8), ("Lanuvio", 0.8),
        ("Rocca di Papa", 0.8), ("Grottaferrata", 0.8), ("Frascati", 0.8),
        ("Rocca Priora", 0.8), ("Monte Porzio Catone", 0.8),
        ("Monte Compatri", 0.8), ("Colonna", 0.8),
        ("Civita Castellana", 0.8), ("Tarquinia", 0.8), ("Montalto di Castro", 0.7),
        ("Vetralla", 0.8), ("Ronciglione", 0.8), ("Nepi", 0.8),
        ("Sutri", 0.8), ("Capranica", 0.8), ("Bassano Romano", 0.8),
        ("Orte", 0.8), ("Tuscania", 0.7), ("Montefiascone", 0.8),
        ("Bolsena", 0.7), ("Acquapendente", 0.7),
        ("Rieti", 0.7), ("Cittaducale", 0.7), ("Poggio Mirteto", 0.7),
        ("Fara in Sabina", 0.8), ("Magliano Sabina", 0.7),
        ("Contigliano", 0.7), ("Greccio", 0.7),
        ("Subiaco", 0.8), ("Palombara Sabina", 0.8), ("Marcellina", 0.8),
        ("San Polo dei Cavalieri", 0.8), ("Vicovaro", 0.8),
        ("Bellegra", 0.8), ("Olevano Romano", 0.8), ("Segni", 0.8),
        ("Gavignano", 0.8), ("Carpineto Romano", 0.8),
        ("Montelanico", 0.8), ("Gorga", 0.8),
    ],

    # ========================================================================
    # CAMPANIA
    # ========================================================================
    "Campania": [
        ("Napoli", 0.8), ("Salerno", 0.8), ("Caserta", 0.8),
        ("Torre del Greco", 0.8), ("Giugliano in Campania", 0.8),
        ("Torre Annunziata", 0.8), ("Castellammare di Stabia", 0.8),
        ("Portici", 0.8), ("Ercolano", 0.8), ("San Giorgio a Cremano", 0.8),
        ("Afragola", 0.8), ("Casoria", 0.8), ("Marano di Napoli", 0.8),
        ("Acerra", 0.8), ("Pozzuoli", 0.8), ("Quarto", 0.8),
        ("Aversa", 0.8), ("Marcianise", 0.8), ("Maddaloni", 0.8),
        ("Santa Maria Capua Vetere", 0.8), ("Capua", 0.8),
        ("San Nicola la Strada", 0.8), ("Casagiove", 0.8),
        ("Mondragone", 0.8), ("Sessa Aurunca", 0.8), ("Carinola", 0.8),
        ("Piedimonte Matese", 0.8), ("Alife", 0.8), ("Caiazzo", 0.8),
        ("Benevento", 0.8), ("Avellino", 0.8),
        ("Ariano Irpino", 0.8), ("Atripalda", 0.8), ("Solofra", 0.8),
        ("Mercogliano", 0.8), ("Montemiletto", 0.8),
        ("Battipaglia", 0.8), ("Nocera Inferiore", 0.8),
        ("Nocera Superiore", 0.8), ("Cava de' Tirreni", 0.8),
        ("Scafati", 0.8), ("Sarno", 0.8), ("Pagani", 0.8),
        ("San Valentino Torio", 0.8), ("Angri", 0.8),
        ("Eboli", 0.8), ("Agropoli", 0.8), ("Capaccio Paestum", 0.8),
        ("Pontecagnano Faiano", 0.8), ("Bellizzi", 0.8), ("Fisciano", 0.8),
        ("Baronissi", 0.8), ("Mercato San Severino", 0.8),
        ("Vietri sul Mare", 0.8), ("Maiori", 0.7), ("Amalfi", 0.7),
        ("Ravello", 0.7), ("Positano", 0.7),
        ("Pompei", 0.8), ("Boscoreale", 0.8), ("Boscotrecase", 0.8),
        ("Trecase", 0.8), ("Sant'Antonio Abate", 0.8),
        ("Sorrento", 0.8), ("Piano di Sorrento", 0.8),
        ("Meta", 0.8), ("Vico Equense", 0.8),
        ("Nola", 0.8), ("Marigliano", 0.8), ("Somma Vesuviana", 0.8),
        ("Ottaviano", 0.8), ("San Giuseppe Vesuviano", 0.8),
        ("Palma Campania", 0.8), ("San Gennaro Vesuviano", 0.8),
        ("Saviano", 0.8), ("Cicciano", 0.8), ("Cimitile", 0.8),
        ("Terzigno", 0.8), ("Poggiomarino", 0.8), ("Striano", 0.8),
        ("San Vitaliano", 0.8), ("Brusciano", 0.8),
        ("Grumo Nevano", 0.8), ("Frattamaggiore", 0.8),
        ("Frattaminore", 0.8), ("Arzano", 0.8), ("Casavatore", 0.8),
        ("Cardito", 0.8), ("Crispano", 0.8), ("Caivano", 0.8),
        ("Sant'Antimo", 0.8), ("Villaricca", 0.8), ("Qualiano", 0.8),
        ("Mugnano di Napoli", 0.8), ("Melito di Napoli", 0.8),
        ("Calvizzano", 0.8), ("Giugliano in Campania", 0.8),
        ("Bacoli", 0.8), ("Monte di Procida", 0.8),
        ("Ischia", 0.8), ("Forio", 0.8), ("Casamicciola Terme", 0.8),
        ("Lacco Ameno", 0.8), ("Barano d'Ischia", 0.8),
        ("Procida", 0.8), ("Capri", 0.8), ("Anacapri", 0.8),
        ("Casalnuovo di Napoli", 0.8), ("Volla", 0.8),
        ("Cercola", 0.8), ("Massa di Somma", 0.8), ("Pollena Trocchia", 0.8),
        ("San Sebastiano al Vesuvio", 0.8),
        ("Trentola Ducenta", 0.8), ("Parete", 0.8), ("Lusciano", 0.8),
        ("Orta di Atella", 0.8), ("Succivo", 0.8), ("Sant'Arpino", 0.8),
        ("Gricignano di Aversa", 0.8), ("Cesa", 0.8),
        ("San Cipriano d'Aversa", 0.8), ("Villa di Briano", 0.8),
        ("Casal di Principe", 0.8), ("San Marcellino", 0.8),
        ("Teverola", 0.8), ("Carinaro", 0.8),
        ("Montesarchio", 0.8), ("Airola", 0.8), ("San Giorgio del Sannio", 0.8),
        ("Telese Terme", 0.8), ("Guardia Sanframondi", 0.8),
        ("Solopaca", 0.8), ("Cerreto Sannita", 0.8),
        ("Sala Consilina", 0.8), ("Sapri", 0.8), ("Vallo della Lucania", 0.8),
        ("Camerota", 0.7), ("Teggiano", 0.8), ("Polla", 0.8),
        ("Padula", 0.8), ("Montesano sulla Marcellana", 0.8),
    ],

    # ========================================================================
    # PUGLIA
    # ========================================================================
    "Puglia": [
        ("Bari", 0.8), ("Lecce", 0.8), ("Taranto", 0.8),
        ("Foggia", 0.8), ("Brindisi", 0.8), ("Andria", 0.8),
        ("Barletta", 0.8), ("Trani", 0.8), ("Altamura", 0.8),
        ("Monopoli", 0.8), ("Molfetta", 0.8), ("Bitonto", 0.8),
        ("Corato", 0.8), ("Ruvo di Puglia", 0.8), ("Terlizzi", 0.8),
        ("Giovinazzo", 0.8), ("Modugno", 0.8), ("Bitetto", 0.8),
        ("Bitritto", 0.8), ("Palo del Colle", 0.8), ("Grumo Appula", 0.8),
        ("Triggiano", 0.8), ("Capurso", 0.8), ("Valenzano", 0.8),
        ("Adelfia", 0.8), ("Casamassima", 0.8), ("Sammichele di Bari", 0.8),
        ("Turi", 0.8), ("Putignano", 0.8), ("Gioia del Colle", 0.8),
        ("Castellana Grotte", 0.8), ("Conversano", 0.8), ("Polignano a Mare", 0.8),
        ("Noci", 0.8), ("Alberobello", 0.8), ("Locorotondo", 0.8),
        ("Fasano", 0.8), ("Cisternino", 0.8), ("Ostuni", 0.8),
        ("Mesagne", 0.8), ("Francavilla Fontana", 0.8),
        ("San Vito dei Normanni", 0.8), ("Ceglie Messapica", 0.8),
        ("Oria", 0.8), ("Latiano", 0.8), ("San Pietro Vernotico", 0.8),
        ("Erchie", 0.8), ("Torre Santa Susanna", 0.8),
        ("San Pancrazio Salentino", 0.8),
        ("Galatina", 0.8), ("Nardò", 0.8), ("Copertino", 0.8),
        ("Gallipoli", 0.8), ("Maglie", 0.8), ("Casarano", 0.8),
        ("Tricase", 0.8), ("Galatone", 0.8), ("Leverano", 0.8),
        ("Veglie", 0.8), ("Campi Salentina", 0.8), ("Surbo", 0.8),
        ("Squinzano", 0.8), ("Trepuzzi", 0.8), ("Novoli", 0.8),
        ("Carmiano", 0.8), ("Arnesano", 0.8), ("Cavallino", 0.8),
        ("Lizzanello", 0.8), ("San Cesario di Lecce", 0.8),
        ("Ugento", 0.8), ("Taviano", 0.8), ("Racale", 0.8),
        ("Melissano", 0.8), ("Alliste", 0.8), ("Matino", 0.8),
        ("Parabita", 0.8), ("Alezio", 0.8), ("Sannicola", 0.8),
        ("San Severo", 0.8), ("Manfredonia", 0.8), ("Cerignola", 0.8),
        ("Lucera", 0.8), ("Orta Nova", 0.8), ("San Giovanni Rotondo", 0.8),
        ("Monte Sant'Angelo", 0.8), ("Vieste", 0.8), ("Mattinata", 0.7),
        ("Apricena", 0.8), ("San Nicandro Garganico", 0.8),
        ("Torremaggiore", 0.8), ("San Paolo di Civitate", 0.8),
        ("Stornara", 0.8), ("Stornarella", 0.8), ("Carapelle", 0.8),
        ("Ascoli Satriano", 0.8), ("Troia", 0.8), ("Bovino", 0.8),
        ("Trinitapoli", 0.8), ("San Ferdinando di Puglia", 0.8),
        ("Margherita di Savoia", 0.8), ("Canosa di Puglia", 0.8),
        ("Minervino Murge", 0.8), ("Spinazzola", 0.8),
        ("Gravina in Puglia", 0.8), ("Santeramo in Colle", 0.8),
        ("Acquaviva delle Fonti", 0.8), ("Cassano delle Murge", 0.8),
        ("Laterza", 0.8), ("Castellaneta", 0.8), ("Ginosa", 0.8),
        ("Massafra", 0.8), ("Mottola", 0.8), ("Grottaglie", 0.8),
        ("Manduria", 0.8), ("Sava", 0.8), ("Avetrana", 0.8),
        ("Fragagnano", 0.8), ("Lizzano", 0.8), ("Pulsano", 0.8),
        ("Leporano", 0.8), ("Statte", 0.8), ("Crispiano", 0.8),
        ("Martina Franca", 0.8), ("Torricella", 0.8),
        ("Maruggio", 0.8), ("San Giorgio Ionico", 0.8),
        ("Carosino", 0.8), ("Monteiasi", 0.8), ("Montemesola", 0.8),
    ],

    # ========================================================================
    # SICILIA
    # ========================================================================
    "Sicilia": [
        ("Palermo", 0.8), ("Catania", 0.8), ("Messina", 0.8),
        ("Siracusa", 0.8), ("Ragusa", 0.7), ("Trapani", 0.8),
        ("Agrigento", 0.8), ("Caltanissetta", 0.8), ("Enna", 0.8),
        ("Marsala", 0.8), ("Gela", 0.8), ("Vittoria", 0.8),
        ("Modica", 0.7), ("Bagheria", 0.8), ("Acireale", 0.8),
        ("Misterbianco", 0.8), ("Paternò", 0.8), ("Adrano", 0.8),
        ("Caltagirone", 0.8), ("Monreale", 0.8), ("Alcamo", 0.8),
        ("Mazara del Vallo", 0.8), ("Licata", 0.8), ("Sciacca", 0.8),
        ("Favara", 0.8), ("Canicattì", 0.8), ("Niscemi", 0.8),
        ("Piazza Armerina", 0.8), ("Barcellona Pozzo di Gotto", 0.8),
        ("Milazzo", 0.8), ("Patti", 0.8), ("Capo d'Orlando", 0.8),
        ("Sant'Agata di Militello", 0.8), ("Lipari", 0.7),
        ("Augusta", 0.8), ("Lentini", 0.8), ("Avola", 0.8),
        ("Noto", 0.8), ("Rosolini", 0.8), ("Pachino", 0.8),
        ("Floridia", 0.8), ("Carlentini", 0.8), ("Priolo Gargallo", 0.8),
        ("Melilli", 0.8), ("Sortino", 0.8),
        ("Comiso", 0.7), ("Scicli", 0.7), ("Ispica", 0.7),
        ("Pozzallo", 0.7), ("Chiaramonte Gulfi", 0.7), ("Santa Croce Camerina", 0.7),
        ("Castelvetrano", 0.8), ("Partanna", 0.8), ("Campobello di Mazara", 0.8),
        ("Salemi", 0.8), ("Gibellina", 0.8), ("Erice", 0.8),
        ("Valderice", 0.8), ("Castellammare del Golfo", 0.8),
        ("San Vito Lo Capo", 0.7), ("Custonaci", 0.8),
        ("Termini Imerese", 0.8), ("Cefalù", 0.8), ("Carini", 0.8),
        ("Partinico", 0.8), ("Villabate", 0.8), ("Ficarazzi", 0.8),
        ("Altofonte", 0.8), ("Misilmeri", 0.8), ("Corleone", 0.8),
        ("Lercara Friddi", 0.8), ("Petralia Sottana", 0.7),
        ("Castelbuono", 0.7), ("Gangi", 0.7), ("Polizzi Generosa", 0.7),
        ("Ribera", 0.8), ("Menfi", 0.8), ("Sambuca di Sicilia", 0.8),
        ("Casteltermini", 0.8), ("San Giovanni Gemini", 0.8),
        ("Cammarata", 0.8), ("Racalmuto", 0.8), ("Grotte", 0.8),
        ("Aragona", 0.8), ("Porto Empedocle", 0.8), ("Realmonte", 0.8),
        ("Raffadali", 0.8), ("Santa Margherita di Belìce", 0.8),
        ("Naro", 0.8), ("Palma di Montechiaro", 0.8),
        ("Piazza Armerina", 0.8), ("Barrafranca", 0.8), ("Leonforte", 0.8),
        ("Nicosia", 0.8), ("Agira", 0.8), ("Centuripe", 0.8),
        ("Biancavilla", 0.8), ("Belpasso", 0.8), ("Mascalucia", 0.8),
        ("Gravina di Catania", 0.8), ("San Giovanni la Punta", 0.8),
        ("Tremestieri Etneo", 0.8), ("Aci Catena", 0.8),
        ("Aci Sant'Antonio", 0.8), ("Aci Castello", 0.8),
        ("San Gregorio di Catania", 0.8), ("Valverde", 0.8),
        ("Pedara", 0.8), ("Nicolosi", 0.8), ("Viagrande", 0.8),
        ("Zafferana Etnea", 0.8), ("Santa Venerina", 0.8),
        ("Giarre", 0.8), ("Riposto", 0.8), ("Mascali", 0.8),
        ("Fiumefreddo di Sicilia", 0.8), ("Calatabiano", 0.8),
        ("Randazzo", 0.8), ("Bronte", 0.8), ("Maletto", 0.8),
        ("Linguaglossa", 0.8), ("Castiglione di Sicilia", 0.7),
        ("Ramacca", 0.8), ("Scordia", 0.8), ("Militello in Val di Catania", 0.8),
        ("Grammichele", 0.8), ("Mineo", 0.8), ("Vizzini", 0.8),
        ("Licodia Eubea", 0.8),
    ],

    # ========================================================================
    # SARDEGNA
    # ========================================================================
    "Sardegna": [
        ("Cagliari", 0.5), ("Sassari", 0.6), ("Quartu Sant'Elena", 0.5),
        ("Olbia", 0.5), ("Alghero", 0.6), ("Nuoro", 0.6),
        ("Oristano", 0.6), ("Carbonia", 0.6), ("Iglesias", 0.6),
        ("Selargius", 0.5), ("Assemini", 0.5), ("Capoterra", 0.5),
        ("Sestu", 0.5), ("Monserrato", 0.5), ("Elmas", 0.5),
        ("Decimomannu", 0.5), ("Sinnai", 0.5), ("Quartucciu", 0.5),
        ("Sarroch", 0.5), ("Pula", 0.5), ("Villa San Pietro", 0.5),
        ("Domus de Maria", 0.5), ("Teulada", 0.5), ("Uta", 0.5),
        ("Maracalagonis", 0.5), ("Settimo San Pietro", 0.5),
        ("Tempio Pausania", 0.6), ("La Maddalena", 0.5),
        ("Arzachena", 0.5), ("Palau", 0.5), ("Santa Teresa Gallura", 0.5),
        ("Budoni", 0.5), ("San Teodoro", 0.5), ("Siniscola", 0.6),
        ("Orosei", 0.6), ("Dorgali", 0.6), ("Orgosolo", 0.6),
        ("Tortolì", 0.6), ("Lanusei", 0.6), ("Jerzu", 0.6),
        ("Baunei", 0.5), ("Lotzorai", 0.6),
        ("Porto Torres", 0.6), ("Sorso", 0.6), ("Sennori", 0.6),
        ("Castelsardo", 0.6), ("Valledoria", 0.5), ("Viddalba", 0.5),
        ("Ozieri", 0.6), ("Thiesi", 0.6), ("Bonorva", 0.6),
        ("Bosa", 0.6), ("Macomer", 0.6), ("Sindia", 0.6),
        ("Terralba", 0.6), ("Marrubiu", 0.6), ("Arborea", 0.5),
        ("Mogoro", 0.6), ("Ales", 0.6), ("Cabras", 0.6),
        ("Santa Giusta", 0.6), ("San Vero Milis", 0.6),
        ("Guspini", 0.6), ("Villacidro", 0.6), ("San Gavino Monreale", 0.6),
        ("Sanluri", 0.6), ("Serramanna", 0.6), ("Serrenti", 0.6),
        ("Samassi", 0.6), ("Sardara", 0.6), ("Gonnosfanadiga", 0.6),
        ("Senorbì", 0.5), ("Isili", 0.6), ("Sorgono", 0.6),
        ("Aritzo", 0.5), ("Tonara", 0.5), ("Desulo", 0.5),
        ("Laconi", 0.6), ("Mandas", 0.6), ("Nurri", 0.6),
        ("Orroli", 0.6), ("Escalaplano", 0.6),
        ("Muravera", 0.5), ("San Vito", 0.5), ("Villaputzu", 0.5),
        ("Villasimius", 0.5), ("Castiadas", 0.5),
        ("Sant'Antioco", 0.6), ("Carloforte", 0.5), ("Calasetta", 0.5),
        ("Portoscuso", 0.6), ("Gonnesa", 0.6),
    ],

    # ========================================================================
    # CALABRIA
    # ========================================================================
    "Calabria": [
        ("Catanzaro", 0.8), ("Reggio Calabria", 0.8), ("Cosenza", 0.8),
        ("Crotone", 0.8), ("Vibo Valentia", 0.8), ("Lamezia Terme", 0.8),
        ("Rende", 0.8), ("Castrovillari", 0.8), ("Rossano", 0.8),
        ("Corigliano-Rossano", 0.8), ("Paola", 0.8), ("Acri", 0.8),
        ("San Giovanni in Fiore", 0.8), ("Montalto Uffugo", 0.8),
        ("Bisignano", 0.8), ("Amantea", 0.8), ("Cetraro", 0.8),
        ("Scalea", 0.8), ("Praia a Mare", 0.8), ("Belvedere Marittimo", 0.8),
        ("Diamante", 0.7), ("Tortora", 0.7),
        ("Gioia Tauro", 0.8), ("Rosarno", 0.8), ("Palmi", 0.8),
        ("Cittanova", 0.8), ("Taurianova", 0.8), ("Polistena", 0.8),
        ("Siderno", 0.8), ("Locri", 0.8), ("Marina di Gioiosa Ionica", 0.8),
        ("Bovalino", 0.8), ("Bianco", 0.8), ("Caulonia", 0.8),
        ("Roccella Ionica", 0.8), ("Stilo", 0.8),
        ("Melito di Porto Salvo", 0.8), ("Bova Marina", 0.8),
        ("Condofuri", 0.8), ("Villa San Giovanni", 0.8),
        ("Scilla", 0.8), ("Bagnara Calabra", 0.8),
        ("Serra San Bruno", 0.8), ("Tropea", 0.7), ("Pizzo", 0.8),
        ("Soverato", 0.8), ("Chiaravalle Centrale", 0.8),
        ("Catanzaro Lido", 0.8), ("Sellia Marina", 0.8),
        ("Botricello", 0.8), ("Cropani", 0.8),
        ("Isola di Capo Rizzuto", 0.8), ("Cutro", 0.8), ("Strongoli", 0.8),
        ("Petilia Policastro", 0.8), ("Mesoraca", 0.8), ("Cirò Marina", 0.8),
        ("Cirò", 0.8), ("Melissa", 0.8), ("Crucoli", 0.8),
        ("Cariati", 0.8), ("Trebisacce", 0.8), ("Cassano all'Ionio", 0.8),
        ("Villapiana", 0.8), ("Amendolara", 0.8),
        ("Lungro", 0.8), ("Spezzano Albanese", 0.8),
        ("San Marco Argentano", 0.8), ("Roggiano Gravina", 0.8),
        ("Torano Castello", 0.8), ("Lattarico", 0.8),
        ("Mendicino", 0.8), ("Carolei", 0.8), ("Dipignano", 0.8),
        ("Grimaldi", 0.8), ("Aprigliano", 0.8), ("Celico", 0.8),
        ("Spezzano della Sila", 0.8), ("Casali del Manco", 0.8),
    ],

    # ========================================================================
    # LIGURIA
    # ========================================================================
    "Liguria": [
        ("Genova", 0.8), ("La Spezia", 0.8), ("Savona", 0.8),
        ("Imperia", 0.7), ("Sanremo", 0.7), ("Rapallo", 0.8),
        ("Chiavari", 0.8), ("Sestri Levante", 0.8), ("Lavagna", 0.8),
        ("Recco", 0.8), ("Camogli", 0.8), ("Santa Margherita Ligure", 0.8),
        ("Portofino", 0.7), ("Sarzana", 0.8), ("Lerici", 0.8),
        ("Arcola", 0.8), ("Santo Stefano di Magra", 0.8),
        ("Bolano", 0.8), ("Vezzano Ligure", 0.8), ("Ameglia", 0.8),
        ("Albenga", 0.8), ("Finale Ligure", 0.8), ("Loano", 0.8),
        ("Pietra Ligure", 0.8), ("Spotorno", 0.8), ("Noli", 0.7),
        ("Varazze", 0.8), ("Celle Ligure", 0.8), ("Albisola Superiore", 0.8),
        ("Albissola Marina", 0.8), ("Vado Ligure", 0.8),
        ("Quiliano", 0.8), ("Cairo Montenotte", 0.8), ("Millesimo", 0.7),
        ("Carcare", 0.8), ("Cengio", 0.8),
        ("Ventimiglia", 0.7), ("Bordighera", 0.7), ("Vallecrosia", 0.7),
        ("Ospedaletti", 0.7), ("Taggia", 0.7), ("Arma di Taggia", 0.7),
        ("Diano Marina", 0.7), ("San Bartolomeo al Mare", 0.7),
        ("Cervo", 0.7), ("Andora", 0.7), ("Laigueglia", 0.7),
        ("Dolceacqua", 0.7), ("Camporosso", 0.7), ("Pigna", 0.7),
        ("Cogoleto", 0.8), ("Arenzano", 0.8), ("Masone", 0.8),
        ("Campo Ligure", 0.8), ("Rossiglione", 0.8), ("Ovada", 0.8),
        ("Busalla", 0.8), ("Ronco Scrivia", 0.8), ("Isola del Cantone", 0.8),
        ("Serra Riccò", 0.8), ("Campomorone", 0.8), ("Ceranesi", 0.8),
        ("Mignanego", 0.8), ("Sant'Olcese", 0.8), ("Bogliasco", 0.8),
        ("Pieve Ligure", 0.8), ("Sori", 0.8), ("Avegno", 0.8),
        ("Uscio", 0.8), ("Cicagna", 0.8), ("Orero", 0.8),
        ("Ne", 0.8), ("Casarza Ligure", 0.8), ("Moneglia", 0.8),
        ("Deiva Marina", 0.8), ("Framura", 0.8), ("Bonassola", 0.8),
        ("Levanto", 0.8), ("Monterosso al Mare", 0.8),
        ("Vernazza", 0.7), ("Riomaggiore", 0.7),
    ],

    # ========================================================================
    # FRIULI VENEZIA GIULIA
    # ========================================================================
    "Friuli Venezia Giulia": [
        ("Trieste", 0.8), ("Udine", 0.5), ("Pordenone", 0.5),
        ("Gorizia", 0.6), ("Monfalcone", 0.6), ("Cordenons", 0.5),
        ("Sacile", 0.5), ("Azzano Decimo", 0.5), ("San Vito al Tagliamento", 0.5),
        ("Spilimbergo", 0.5), ("Maniago", 0.5), ("Brugnera", 0.5),
        ("Fontanafredda", 0.5), ("Porcia", 0.5), ("Roveredo in Piano", 0.5),
        ("Aviano", 0.5), ("Fiume Veneto", 0.5), ("Pasiano di Pordenone", 0.5),
        ("Casarsa della Delizia", 0.5), ("Valvasone Arzene", 0.5),
        ("Codroipo", 0.5), ("Latisana", 0.5), ("Palmanova", 0.5),
        ("Cervignano del Friuli", 0.5), ("Tavagnacco", 0.5),
        ("Campoformido", 0.5), ("Pagnacco", 0.5), ("Pasian di Prato", 0.5),
        ("Remanzacco", 0.5), ("Pradamano", 0.5), ("Buttrio", 0.5),
        ("Manzano", 0.5), ("San Giovanni al Natisone", 0.5),
        ("Cividale del Friuli", 0.5), ("San Daniele del Friuli", 0.5),
        ("Gemona del Friuli", 0.5), ("Tolmezzo", 0.5), ("Amaro", 0.5),
        ("Tarvisio", 0.5), ("Pontebba", 0.5), ("Moggio Udinese", 0.5),
        ("Tarcento", 0.5), ("Tricesimo", 0.5), ("Feletto Umberto", 0.5),
        ("Martignacco", 0.5), ("Fagagna", 0.5), ("Majano", 0.5),
        ("Trasaghis", 0.5), ("Osoppo", 0.5), ("Artegna", 0.5),
        ("Gradisca d'Isonzo", 0.6), ("Staranzano", 0.6),
        ("Ronchi dei Legionari", 0.6), ("San Canzian d'Isonzo", 0.6),
        ("Cormons", 0.6), ("San Lorenzo Isontino", 0.6),
        ("Farra d'Isonzo", 0.6), ("Sagrado", 0.6),
        ("Muggia", 0.8), ("San Dorligo della Valle", 0.8),
        ("Duino-Aurisina", 0.7), ("Sgonico", 0.7),
        ("Lignano Sabbiadoro", 0.5), ("Marano Lagunare", 0.5),
        ("Aquileia", 0.5), ("Grado", 0.5), ("Torviscosa", 0.5),
        ("Gonars", 0.5), ("Bagnaria Arsa", 0.5),
        ("Rivignano Teor", 0.5), ("Varmo", 0.5), ("Basiliano", 0.5),
        ("Lestizza", 0.5), ("Mortegliano", 0.5), ("Pavia di Udine", 0.5),
        ("Sedegliano", 0.5), ("Mereto di Tomba", 0.5),
    ],

    # ========================================================================
    # MARCHE
    # ========================================================================
    "Marche": [
        ("Ancona", 0.8), ("Pesaro", 0.8), ("Fano", 0.8),
        ("Ascoli Piceno", 0.8), ("Macerata", 0.8), ("Fermo", 0.8),
        ("San Benedetto del Tronto", 0.8), ("Civitanova Marche", 0.8),
        ("Jesi", 0.8), ("Senigallia", 0.8), ("Fabriano", 0.8),
        ("Osimo", 0.8), ("Falconara Marittima", 0.8),
        ("Recanati", 0.8), ("Loreto", 0.8), ("Castelfidardo", 0.8),
        ("Porto Recanati", 0.8), ("Potenza Picena", 0.8),
        ("Tolentino", 0.8), ("Corridonia", 0.8), ("San Severino Marche", 0.8),
        ("Camerino", 0.8), ("Cingoli", 0.8), ("Matelica", 0.8),
        ("Pollenza", 0.8), ("Treia", 0.8),
        ("Porto Sant'Elpidio", 0.8), ("Sant'Elpidio a Mare", 0.8),
        ("Montegranaro", 0.8), ("Monte Urano", 0.8),
        ("Montegiorgio", 0.8), ("Amandola", 0.8), ("Servigliano", 0.8),
        ("Grottammare", 0.8), ("Cupra Marittima", 0.8),
        ("Ripatransone", 0.8), ("Montalto delle Marche", 0.8),
        ("Offida", 0.8), ("Acquasanta Terme", 0.8), ("Arquata del Tronto", 0.8),
        ("Comunanza", 0.8), ("Force", 0.8), ("Monteprandone", 0.8),
        ("Monsampaolo del Tronto", 0.8), ("Castel di Lama", 0.8),
        ("Colli del Tronto", 0.8), ("Spinetoli", 0.8), ("Monsampolo del Tronto", 0.8),
        ("Urbino", 0.8), ("Fossombrone", 0.8), ("Cagli", 0.8),
        ("Pergola", 0.8), ("Urbania", 0.8), ("Sant'Angelo in Vado", 0.8),
        ("Mercatino Conca", 0.8), ("Vallefoglia", 0.8),
        ("Tavullia", 0.8), ("Gabicce Mare", 0.8), ("Gradara", 0.8),
        ("Mondolfo", 0.8), ("Corinaldo", 0.8), ("Arcevia", 0.8),
        ("Sassoferrato", 0.8), ("Serra San Quirico", 0.8),
        ("Chiaravalle", 0.8), ("Monte San Vito", 0.8), ("Agugliano", 0.8),
        ("Polverigi", 0.8), ("Camerata Picena", 0.8), ("Offagna", 0.8),
        ("Filottrano", 0.8), ("Staffolo", 0.8), ("Cupramontana", 0.8),
        ("Maiolati Spontini", 0.8), ("Castelplanio", 0.8),
        ("Montecarotto", 0.8), ("San Marcello", 0.8), ("Monsano", 0.8),
        ("Monte Roberto", 0.8), ("Apiro", 0.8), ("Mergo", 0.8),
        ("Porto San Giorgio", 0.8), ("Pedaso", 0.8), ("Altidona", 0.8),
        ("Lapedona", 0.8), ("Moresco", 0.8),
    ],

    # ========================================================================
    # ABRUZZO
    # ========================================================================
    "Abruzzo": [
        ("L'Aquila", 0.8), ("Pescara", 0.8), ("Chieti", 0.8),
        ("Teramo", 0.7), ("Avezzano", 0.8), ("Lanciano", 0.8),
        ("Vasto", 0.8), ("Sulmona", 0.8), ("Montesilvano", 0.8),
        ("Francavilla al Mare", 0.8), ("Ortona", 0.8),
        ("San Salvo", 0.8), ("Giulianova", 0.7), ("Roseto degli Abruzzi", 0.7),
        ("Silvi", 0.7), ("Pineto", 0.7), ("Alba Adriatica", 0.7),
        ("Martinsicuro", 0.7), ("Tortoreto", 0.7), ("Nereto", 0.7),
        ("Corropoli", 0.7), ("Colonnella", 0.7), ("Controguerra", 0.7),
        ("Sant'Egidio alla Vibrata", 0.7), ("Ancarano", 0.7),
        ("Atri", 0.7), ("Campli", 0.7), ("Civitella del Tronto", 0.7),
        ("Bellante", 0.7), ("Mosciano Sant'Angelo", 0.7),
        ("Notaresco", 0.7), ("Morro d'Oro", 0.7), ("Canzano", 0.7),
        ("Castellalto", 0.7), ("Isola del Gran Sasso d'Italia", 0.7),
        ("Spoltore", 0.8), ("Cappelle sul Tavo", 0.8),
        ("Città Sant'Angelo", 0.8), ("Collecorvino", 0.8),
        ("Loreto Aprutino", 0.8), ("Penne", 0.8), ("Pianella", 0.8),
        ("Cepagatti", 0.8), ("Rosciano", 0.8), ("Nocciano", 0.8),
        ("Manoppello", 0.8), ("Scafa", 0.8), ("Alanno", 0.8),
        ("Tocco da Casauria", 0.8), ("Popoli", 0.8), ("Torre de' Passeri", 0.8),
        ("Bolognano", 0.8), ("San Valentino in Abruzzo Citeriore", 0.8),
        ("Guardiagrele", 0.8), ("Casoli", 0.8), ("Atessa", 0.8),
        ("Fossacesia", 0.8), ("Castel Frentano", 0.8), ("Paglieta", 0.8),
        ("Torrevecchia Teatina", 0.8), ("Ripa Teatina", 0.8),
        ("Miglianico", 0.8), ("Tollo", 0.8), ("Orsogna", 0.8),
        ("Crecchio", 0.8), ("Arielli", 0.8), ("Canosa Sannita", 0.8),
        ("Villamagna", 0.8), ("Bucchianico", 0.8), ("Fara Filiorum Petri", 0.8),
        ("Roccamontepiano", 0.8), ("Rapino", 0.8), ("Pretoro", 0.8),
        ("Celano", 0.8), ("Trasacco", 0.8), ("Luco dei Marsi", 0.8),
        ("Tagliacozzo", 0.8), ("Carsoli", 0.8), ("Magliano de' Marsi", 0.8),
        ("Pratola Peligna", 0.8), ("Introdacqua", 0.8), ("Pettorano sul Gizio", 0.8),
        ("Castel di Sangro", 0.8), ("Roccaraso", 0.7), ("Scanno", 0.7),
        ("Pescasseroli", 0.7),
    ],

    # ========================================================================
    # UMBRIA
    # ========================================================================
    "Umbria": [
        ("Perugia", 0.8), ("Terni", 0.8), ("Foligno", 0.8),
        ("Città di Castello", 0.7), ("Spoleto", 0.8), ("Gubbio", 0.8),
        ("Assisi", 0.8), ("Bastia Umbra", 0.8), ("Orvieto", 0.8),
        ("Narni", 0.8), ("Amelia", 0.8), ("Marsciano", 0.8),
        ("Todi", 0.8), ("Umbertide", 0.8), ("Magione", 0.8),
        ("Corciano", 0.8), ("Deruta", 0.8), ("San Giustino", 0.7),
        ("Castiglione del Lago", 0.8), ("Passignano sul Trasimeno", 0.8),
        ("Tuoro sul Trasimeno", 0.8), ("Città della Pieve", 0.8),
        ("Panicale", 0.8), ("Piegaro", 0.8),
        ("Spello", 0.8), ("Trevi", 0.8), ("Montefalco", 0.8),
        ("Bevagna", 0.8), ("Nocera Umbra", 0.8), ("Gualdo Tadino", 0.8),
        ("Valtopina", 0.8), ("Sellano", 0.7), ("Cerreto di Spoleto", 0.7),
        ("Norcia", 0.7), ("Cascia", 0.7), ("Preci", 0.7),
        ("Montone", 0.7), ("Pietralunga", 0.7), ("Scheggia e Pascelupo", 0.7),
        ("Costacciaro", 0.7), ("Sigillo", 0.7), ("Fossato di Vico", 0.8),
        ("Gualdo Cattaneo", 0.8), ("Giano dell'Umbria", 0.8),
        ("Campello sul Clitunno", 0.8), ("Scheggino", 0.7),
        ("Sant'Anatolia di Narco", 0.7), ("Vallo di Nera", 0.7),
        ("Massa Martana", 0.8), ("Acquasparta", 0.8), ("San Gemini", 0.8),
        ("Montecastrilli", 0.8), ("Calvi dell'Umbria", 0.8),
        ("Otricoli", 0.8), ("Stroncone", 0.8), ("Arrone", 0.8),
        ("Ferentillo", 0.8), ("Polino", 0.7), ("Montefranco", 0.8),
        ("Alviano", 0.8), ("Guardea", 0.8), ("Lugnano in Teverina", 0.8),
        ("Attigliano", 0.8), ("Giove", 0.8), ("Penna in Teverina", 0.8),
        ("Baschi", 0.8), ("Montecchio", 0.8), ("Allerona", 0.8),
        ("Castel Viscardo", 0.8), ("Fabro", 0.8), ("Ficulle", 0.8),
        ("Parrano", 0.7), ("San Venanzo", 0.8), ("Monte Castello di Vibio", 0.8),
        ("Fratta Todina", 0.8), ("Collazzone", 0.8),
    ],

    # ========================================================================
    # TRENTINO-ALTO ADIGE
    # ========================================================================
    "Trentino-Alto Adige": [
        ("Trento", 0.5), ("Bolzano", 0.2), ("Rovereto", 0.5),
        ("Merano", 0.2), ("Bressanone", 0.2), ("Laives", 0.2),
        ("Pergine Valsugana", 0.5), ("Arco", 0.5), ("Riva del Garda", 0.5),
        ("Mori", 0.5), ("Ala", 0.5), ("Levico Terme", 0.5),
        ("Borgo Valsugana", 0.5), ("Cavalese", 0.5), ("Predazzo", 0.5),
        ("Moena", 0.4), ("Canazei", 0.4), ("Pozza di Fassa", 0.4),
        ("Cles", 0.5), ("Malè", 0.5), ("Tione di Trento", 0.5),
        ("Storo", 0.5), ("Condino", 0.5), ("Pinzolo", 0.4),
        ("Madonna di Campiglio", 0.4), ("Mezzolombardo", 0.5),
        ("Mezzocorona", 0.5), ("San Michele all'Adige", 0.5),
        ("Lavis", 0.5), ("Aldeno", 0.5), ("Calliano", 0.5),
        ("Besenello", 0.5), ("Volano", 0.5), ("Isera", 0.5),
        ("Nomi", 0.5), ("Villa Lagarina", 0.5), ("Nogaredo", 0.5),
        ("Pomarolo", 0.5),
        ("Appiano sulla Strada del Vino", 0.2), ("Caldaro sulla Strada del Vino", 0.2),
        ("Egna", 0.2), ("Ora", 0.2), ("Termeno sulla Strada del Vino", 0.2),
        ("Cortaccia sulla Strada del Vino", 0.2), ("Magrè sulla Strada del Vino", 0.2),
        ("Salorno", 0.2), ("Bronzolo", 0.2), ("Vadena", 0.2),
        ("Brunico", 0.2), ("San Candido", 0.2), ("Dobbiaco", 0.2),
        ("Monguelfo-Tesido", 0.2), ("San Lorenzo di Sebato", 0.2),
        ("Vipiteno", 0.2), ("Fortezza", 0.2), ("Campo di Trens", 0.2),
        ("Brennero", 0.2), ("Racines", 0.2),
        ("Silandro", 0.2), ("Laces", 0.2), ("Naturno", 0.2),
        ("Lana", 0.2), ("Cermes", 0.2), ("Tirolo", 0.2),
        ("Lagundo", 0.2), ("Parcines", 0.2), ("Marlengo", 0.2),
        ("Scena", 0.2), ("San Leonardo in Passiria", 0.2),
        ("Castelrotto", 0.2), ("Ortisei", 0.2), ("Santa Cristina Valgardena", 0.2),
        ("Selva di Val Gardena", 0.2), ("Chiusa", 0.2), ("Barbiano", 0.2),
        ("Ponte Gardena", 0.2), ("Laion", 0.2), ("Villandro", 0.2),
        ("Nova Ponente", 0.2), ("Nova Levante", 0.2), ("Tires", 0.2),
        ("Fiè allo Sciliar", 0.2), ("Renon", 0.2), ("Sarentino", 0.2),
        ("San Genesio Atesino", 0.2), ("Postal", 0.2), ("Gargazzone", 0.2),
        ("Tesimo", 0.2), ("Cermes", 0.2), ("Andriano", 0.2),
        ("Terlano", 0.2), ("Nalles", 0.2), ("Meltina", 0.2),
        ("San Pancrazio", 0.2), ("Ultimo", 0.2), ("Proves", 0.2),
        ("Senales", 0.2),
    ],

    # ========================================================================
    # MOLISE
    # ========================================================================
    "Molise": [
        ("Campobasso", 0.8), ("Isernia", 0.8), ("Termoli", 0.8),
        ("Bojano", 0.8), ("Venafro", 0.8), ("Larino", 0.8),
        ("Agnone", 0.8), ("Riccia", 0.8), ("Trivento", 0.8),
        ("Montenero di Bisaccia", 0.8), ("Guglionesi", 0.8),
        ("Campomarino", 0.8), ("Petacciato", 0.8), ("San Martino in Pensilis", 0.8),
        ("Portocannone", 0.8), ("Ururi", 0.8),
        ("Frosolone", 0.8), ("Carpinone", 0.8), ("Macchiagodena", 0.8),
        ("Cerro al Volturno", 0.8), ("Colli a Volturno", 0.8),
        ("Monteroduni", 0.8), ("Filignano", 0.8), ("Fornelli", 0.8),
        ("Vinchiaturo", 0.8), ("Baranello", 0.8), ("Busso", 0.8),
        ("Ferrazzano", 0.8), ("Mirabello Sannitico", 0.8),
        ("Montagano", 0.8), ("Limosano", 0.8), ("Ripalimosani", 0.8),
        ("Jelsi", 0.8), ("Gambatesa", 0.8), ("Toro", 0.8),
        ("Pietracatella", 0.8), ("San Giuliano di Puglia", 0.8),
        ("Bonefro", 0.8), ("Santa Croce di Magliano", 0.8),
        ("Colletorto", 0.8), ("Rotello", 0.8), ("San Giuliano del Sannio", 0.8),
    ],

    # ========================================================================
    # BASILICATA
    # ========================================================================
    "Basilicata": [
        ("Potenza", 0.8), ("Matera", 0.8), ("Melfi", 0.6),
        ("Pisticci", 0.8), ("Policoro", 0.8), ("Lauria", 0.8),
        ("Avigliano", 0.8), ("Rionero in Vulture", 0.8),
        ("Venosa", 0.7), ("Lavello", 0.8), ("Bernalda", 0.8),
        ("Ferrandina", 0.8), ("Tricarico", 0.8), ("Irsina", 0.8),
        ("Montescaglioso", 0.8), ("Grassano", 0.8), ("Grottole", 0.8),
        ("Lagonegro", 0.8), ("Maratea", 0.7), ("Senise", 0.8),
        ("Chiaromonte", 0.8), ("Latronico", 0.8), ("Castelluccio Inferiore", 0.8),
        ("Castelluccio Superiore", 0.8), ("Rotonda", 0.8),
        ("Viggianello", 0.7), ("San Severino Lucano", 0.7),
        ("Francavilla in Sinni", 0.8), ("Noepoli", 0.8),
        ("Tursi", 0.8), ("Stigliano", 0.8), ("Colobraro", 0.8),
        ("Valsinni", 0.8), ("San Giorgio Lucano", 0.8),
        ("Nova Siri", 0.8), ("Rotondella", 0.8), ("Scanzano Jonico", 0.8),
        ("Muro Lucano", 0.8), ("Pescopagano", 0.8), ("Rapone", 0.8),
        ("Ruvo del Monte", 0.8), ("San Fele", 0.8), ("Atella", 0.7),
        ("Barile", 0.7), ("Rapolla", 0.7), ("Ginestra", 0.7),
        ("Palazzo San Gervasio", 0.8), ("Banzi", 0.8), ("Genzano di Lucania", 0.8),
        ("Oppido Lucano", 0.8), ("Acerenza", 0.8), ("Forenza", 0.8),
        ("Tolve", 0.8), ("San Chirico Nuovo", 0.8), ("Cancellara", 0.8),
        ("Pietragalla", 0.8), ("Filiano", 0.8), ("Ruoti", 0.8),
        ("Picerno", 0.8), ("Tito", 0.8), ("Satriano di Lucania", 0.8),
        ("Sant'Angelo le Fratte", 0.8), ("Brienza", 0.8), ("Sasso di Castalda", 0.8),
        ("Marsico Nuovo", 0.8), ("Viggiano", 0.8), ("Grumento Nova", 0.8),
        ("Moliterno", 0.8), ("Sarconi", 0.8), ("Paterno", 0.8),
        ("Tramutola", 0.8), ("Marsicovetere", 0.8), ("Villa d'Agri", 0.8),
    ],

    # ========================================================================
    # VALLE D'AOSTA
    # ========================================================================
    "Valle d'Aosta": [
        ("Aosta", 0.5), ("Châtillon", 0.3), ("Saint-Vincent", 0.3),
        ("Sarre", 0.3), ("Gressan", 0.3), ("Charvensod", 0.3),
        ("Pollein", 0.3), ("Brissogne", 0.3), ("Quart", 0.3),
        ("Saint-Christophe", 0.3), ("Fénis", 0.3), ("Nus", 0.3),
        ("Villeneuve", 0.3), ("Aymavilles", 0.3), ("Cogne", 0.3),
        ("Valtournenche", 0.3), ("Gressoney-La-Trinité", 0.3),
        ("Gressoney-Saint-Jean", 0.3), ("Brusson", 0.3),
        ("Challand-Saint-Victor", 0.3), ("Challand-Saint-Anselme", 0.3),
        ("Verrès", 0.3), ("Issogne", 0.3), ("Arnad", 0.3),
        ("Hône", 0.3), ("Bard", 0.3), ("Donnas", 0.3),
        ("Pont-Saint-Martin", 0.3), ("Morgex", 0.3), ("La Thuile", 0.3),
        ("Pré-Saint-Didier", 0.3), ("Courmayeur", 0.3),
        ("La Salle", 0.3), ("Derby", 0.3), ("Avise", 0.3),
        ("Introd", 0.3), ("Rhêmes-Notre-Dame", 0.3),
        ("Rhêmes-Saint-Georges", 0.3), ("Valsavarenche", 0.3),
        ("Étroubles", 0.3), ("Saint-Oyen", 0.3), ("Saint-Rhémy-en-Bosses", 0.3),
        ("Doues", 0.3), ("Ollomont", 0.3), ("Valpelline", 0.3),
        ("Roisan", 0.3), ("Gignod", 0.3), ("Allein", 0.3),
        ("Saint-Pierre", 0.3), ("Saint-Nicolas", 0.3), ("Avise", 0.3),
        ("Champdepraz", 0.3), ("Montjovet", 0.3), ("Saint-Denis", 0.3),
        ("Chambave", 0.3), ("Pontey", 0.3), ("Saint-Marcel", 0.3),
        ("Antey-Saint-André", 0.3), ("Torgnon", 0.3), ("Chamois", 0.3),
        ("La Magdeleine", 0.3),
    ],

    # ========================================================================
    # Additional comuni to reach 2000+ total
    # ========================================================================

    # More LOMBARDIA comuni
    "Lombardia_extra": [
        ("Carugate", 0.8), ("Pessano con Bornago", 0.8),
        ("Cambiago", 0.8), ("Bellusco", 0.8), ("Mezzago", 0.7),
        ("Sulbiate", 0.7), ("Cornate d'Adda", 0.8), ("Burago di Molgora", 0.8),
        ("Caponago", 0.8), ("Bussero", 0.8), ("Cassano d'Adda", 0.8),
        ("Vaprio d'Adda", 0.8), ("Pozzo d'Adda", 0.8), ("Truccazzano", 0.8),
        ("Liscate", 0.8), ("Settala", 0.8), ("Rodano", 0.8),
        ("Vignate", 0.8), ("Tribiano", 0.8), ("Colturano", 0.8),
        ("Dresano", 0.8), ("San Zenone al Lambro", 0.8),
        ("Cerro al Lambro", 0.8), ("Carpiano", 0.7),
        ("Landriano", 0.7), ("Siziano", 0.7), ("Casarile", 0.8),
        ("Noviglio", 0.8), ("Vernate", 0.7), ("Rosate", 0.8),
        ("Motta Visconti", 0.8), ("Besate", 0.7), ("Morimondo", 0.7),
        ("Ozzero", 0.7), ("Albairate", 0.7), ("Cisliano", 0.7),
        ("Cusago", 0.8), ("Bareggio", 0.8), ("Cornaredo", 0.8),
        ("Settimo Milanese", 0.8), ("Pero", 0.8), ("Pregnana Milanese", 0.8),
        ("Vanzago", 0.8), ("Arluno", 0.8), ("Ossona", 0.8),
        ("Marcallo con Casone", 0.8), ("Mesero", 0.8), ("Inveruno", 0.8),
        ("Cuggiono", 0.8), ("Bernate Ticino", 0.8), ("Boffalora sopra Ticino", 0.8),
        ("Robecchetto con Induno", 0.8), ("Castano Primo", 0.8),
        ("Turbigo", 0.8), ("Nosate", 0.7), ("Vanzaghello", 0.8),
        ("Magnago", 0.8), ("Dairago", 0.8), ("Villa Cortese", 0.8),
        ("Busto Garolfo", 0.8), ("Canegrate", 0.8), ("San Giorgio su Legnano", 0.8),
        ("Nerviano", 0.8), ("Pogliano Milanese", 0.8), ("Vanzago", 0.8),
        ("Casorezzo", 0.8), ("Sedriano", 0.8), ("Vittuone", 0.8),
        ("Corbetta", 0.8), ("Santo Stefano Ticino", 0.8),
        ("Robecco sul Naviglio", 0.8), ("Castelletto di Cuggiono", 0.8),
        ("Travacò Siccomario", 0.7), ("San Martino Siccomario", 0.7),
        ("Cura Carpignano", 0.7), ("Certosa di Pavia", 0.7),
        ("Borgarello", 0.7), ("Giussago", 0.7), ("Battuda", 0.7),
        ("Bereguardo", 0.7), ("Trivolzio", 0.7), ("Marcignago", 0.7),
        ("Cassolnovo", 0.7), ("Gambolò", 0.7), ("Garlasco", 0.7),
        ("Dorno", 0.7), ("Lomello", 0.7), ("Sannazzaro de' Burgondi", 0.7),
        ("Scaldasole", 0.7), ("Ottobiano", 0.7), ("Robbio", 0.7),
    ],

    # More PIEMONTE comuni
    "Piemonte_extra": [
        ("Giaveno", 0.8), ("Coazze", 0.8), ("Valgioie", 0.8),
        ("Trana", 0.8), ("Reano", 0.8), ("Sangano", 0.8),
        ("Bruino", 0.8), ("Volvera", 0.8), ("Piossasco", 0.8),
        ("Cumiana", 0.8), ("Frossasco", 0.8), ("Roletto", 0.8),
        ("Cantalupa", 0.8), ("San Pietro Val Lemina", 0.8),
        ("Prarostino", 0.8), ("San Secondo di Pinerolo", 0.8),
        ("Bricherasio", 0.8), ("Luserna San Giovanni", 0.8),
        ("Torre Pellice", 0.8), ("Lusernetta", 0.7),
        ("Bibiana", 0.8), ("Garzigliana", 0.8), ("Osasco", 0.8),
        ("Buriasco", 0.8), ("Macello", 0.8), ("Scalenghe", 0.8),
        ("Airasca", 0.8), ("Virle Piemonte", 0.8), ("Cercenasco", 0.8),
        ("Villastellone", 0.8), ("Pancalieri", 0.8),
        ("Castagnole Piemonte", 0.8), ("Lombriasco", 0.8),
        ("Murello", 0.8), ("Cavallermaggiore", 0.7), ("Marene", 0.7),
        ("Genola", 0.7), ("Villafalletto", 0.7), ("Costigliole Saluzzo", 0.7),
        ("Manta", 0.7), ("Verzuolo", 0.7), ("Piasco", 0.7),
        ("Envie", 0.7), ("Revello", 0.7), ("Martiniana Po", 0.7),
        ("Sanfront", 0.7), ("Paesana", 0.7), ("Bagnolo Piemonte", 0.7),
        ("Cavallino", 0.7), ("Centallo", 0.7), ("Tarantasca", 0.7),
        ("Borgo San Dalmazzo", 0.6), ("Demonte", 0.6), ("Vinadio", 0.6),
        ("Valdieri", 0.6), ("Limone Piemonte", 0.6), ("Vernante", 0.6),
    ],

    # More VENETO comuni
    "Veneto_extra": [
        ("Scorzè", 0.8), ("Salzano", 0.8), ("Vigonovo", 0.8),
        ("Fiesso d'Artico", 0.8), ("Fossò", 0.8), ("Camponogara", 0.8),
        ("Campagna Lupia", 0.8), ("Pianiga", 0.8), ("Mira", 0.8),
        ("Cavarzere", 0.8), ("Cona", 0.8), ("Tribano", 0.8),
        ("Agna", 0.8), ("Candiana", 0.8), ("Stanghella", 0.8),
        ("Bagnoli di Sopra", 0.8), ("Arre", 0.8), ("Cartura", 0.8),
        ("Battaglia Terme", 0.8), ("Galzignano Terme", 0.8),
        ("Torreglia", 0.7), ("Teolo", 0.7), ("Vo'", 0.7),
        ("Cervarese Santa Croce", 0.7), ("Rovolon", 0.7),
        ("Saccolongo", 0.7), ("Mestrino", 0.8), ("Veggiano", 0.7),
        ("Villafranca Padovana", 0.8), ("Campodarsego", 0.8),
        ("Borgoricco", 0.8), ("Massanzago", 0.8), ("Santa Giustina in Colle", 0.8),
        ("San Giorgio delle Pertiche", 0.8), ("Curtarolo", 0.8),
        ("Campo San Martino", 0.8), ("Villa del Conte", 0.7),
        ("Gazzo", 0.7), ("Grantorto", 0.7), ("Carmignano di Brenta", 0.7),
        ("Fontaniva", 0.7), ("San Pietro in Gu", 0.7),
        ("Tombolo", 0.7), ("Galliera Veneta", 0.7), ("San Martino di Lupari", 0.7),
        ("Loreggia", 0.7), ("Resana", 0.7), ("Piombino Dese", 0.7),
        ("Trebaseleghe", 0.8), ("Camposampiero", 0.8), ("Noale", 0.8),
        ("Santa Maria di Sala", 0.8), ("Vigonza", 0.8),
        ("Noventa di Piave", 0.8), ("Musile di Piave", 0.8),
        ("Eraclea", 0.8), ("Torre di Mosto", 0.8), ("Ceggia", 0.8),
        ("Cessalto", 0.7), ("Chiarano", 0.7), ("Gorgo al Monticano", 0.7),
        ("Motta di Livenza", 0.7), ("Meduna di Livenza", 0.7),
        ("Mansuè", 0.7), ("Portobuffolè", 0.7), ("Codognè", 0.7),
        ("San Fior", 0.7), ("Mareno di Piave", 0.7), ("Vazzola", 0.7),
        ("San Polo di Piave", 0.7), ("Ormelle", 0.7), ("Salgareda", 0.7),
        ("Breda di Piave", 0.7), ("San Biagio di Callalta", 0.7),
        ("Monastier di Treviso", 0.7), ("Zenson di Piave", 0.7),
    ],

    # More EMILIA-ROMAGNA comuni
    "Emilia-Romagna_extra": [
        ("Castel San Pietro Terme", 0.8), ("Dozza", 0.8),
        ("Ozzano dell'Emilia", 0.8), ("San Lazzaro di Savena", 0.8),
        ("Monterenzio", 0.8), ("Loiano", 0.8), ("Monghidoro", 0.8),
        ("San Benedetto Val di Sambro", 0.8), ("Marzabotto", 0.8),
        ("Vergato", 0.8), ("Grizzana Morandi", 0.8),
        ("Castiglione dei Pepoli", 0.8), ("Camugnano", 0.8),
        ("Porretta Terme", 0.8), ("Gaggio Montano", 0.8),
        ("Lizzano in Belvedere", 0.8), ("Fanano", 0.7),
        ("Sestola", 0.7), ("Montecreto", 0.7), ("Riolunato", 0.7),
        ("Pievepelago", 0.7), ("Frassinoro", 0.7), ("Prignano sulla Secchia", 0.7),
        ("Palagano", 0.7), ("Montefiorino", 0.7), ("Polinago", 0.7),
        ("Serramazzoni", 0.7), ("Guiglia", 0.7), ("Zocca", 0.7),
        ("Montese", 0.7), ("Marano sul Panaro", 0.7),
        ("Savignano sul Panaro", 0.7), ("Bazzano", 0.8),
        ("Crespellano", 0.8), ("Monte San Pietro", 0.8),
        ("Monteveglio", 0.8), ("Castello di Serravalle", 0.8),
        ("Savigno", 0.8), ("Sala Bolognese", 0.8), ("Calderara di Reno", 0.8),
        ("Castel Maggiore", 0.8), ("Bentivoglio", 0.8),
        ("San Giorgio di Piano", 0.8), ("Galliera", 0.8),
        ("Pieve di Cento", 0.8), ("San Pietro in Casale", 0.8),
        ("Castel d'Argile", 0.8), ("Argelato", 0.8),
        ("Comacchio", 0.8), ("Portomaggiore", 0.8), ("Ostellato", 0.8),
        ("Lagosanto", 0.8), ("Mesola", 0.8), ("Goro", 0.8),
        ("Jolanda di Savoia", 0.8), ("Tresigallo", 0.8), ("Formignana", 0.8),
        ("Ro", 0.8), ("Berra", 0.8), ("Voghiera", 0.8),
        ("Masi Torello", 0.8), ("Vigarano Mainarda", 0.8),
    ],

    # More TOSCANA comuni
    "Toscana_extra": [
        ("Calci", 0.8), ("Vecchiano", 0.8), ("San Giuliano Terme", 0.8),
        ("Fauglia", 0.8), ("Crespina", 0.8), ("Lari", 0.8),
        ("Terricciola", 0.8), ("Chianni", 0.7), ("Lajatico", 0.7),
        ("Palaia", 0.8), ("Montaione", 0.7), ("Gambassi Terme", 0.7),
        ("Barberino Val d'Elsa", 0.7), ("Tavarnelle Val di Pesa", 0.7),
        ("Radda in Chianti", 0.6), ("Gaiole in Chianti", 0.6),
        ("Castellina in Chianti", 0.6), ("Monteriggioni", 0.7),
        ("Casole d'Elsa", 0.7), ("Radicondoli", 0.7), ("Chiusdino", 0.7),
        ("Monticiano", 0.7), ("Murlo", 0.7), ("Buonconvento", 0.7),
        ("San Giovanni d'Asso", 0.7), ("Pienza", 0.6), ("San Quirico d'Orcia", 0.6),
        ("Castiglione d'Orcia", 0.7), ("Abbadia San Salvatore", 0.7),
        ("Piancastagnaio", 0.7), ("Radicofani", 0.7), ("Cetona", 0.7),
        ("Sarteano", 0.7), ("Chianciano Terme", 0.7), ("San Casciano dei Bagni", 0.6),
        ("Torrita di Siena", 0.7), ("Trequanda", 0.7),
        ("Montepulciano", 0.7), ("Chiusi", 0.7),
        ("Sansepolcro", 0.8), ("Anghiari", 0.8), ("Monterchi", 0.8),
        ("Caprese Michelangelo", 0.8), ("Pieve Santo Stefano", 0.8),
        ("Badia Tedalda", 0.7), ("Sestino", 0.7),
        ("Castel Focognano", 0.8), ("Subbiano", 0.8), ("Capolona", 0.8),
        ("Castel San Niccolò", 0.8), ("Pratovecchio Stia", 0.8),
        ("Poppi", 0.8), ("Bibbiena", 0.8), ("Ortignano Raggiolo", 0.8),
        ("Chitignano", 0.8), ("Talla", 0.8), ("Castel Focognano", 0.8),
    ],

    # More LAZIO comuni
    "Lazio_extra": [
        ("Amatrice", 0.7), ("Accumoli", 0.7), ("Leonessa", 0.7),
        ("Borgorose", 0.7), ("Pescorocchiano", 0.7),
        ("Fiamignano", 0.7), ("Petrella Salto", 0.7),
        ("Antrodoco", 0.7), ("Borgo Velino", 0.7), ("Castel Sant'Angelo", 0.7),
        ("Cantalice", 0.7), ("Poggio Bustone", 0.7), ("Rivodutri", 0.7),
        ("Labro", 0.7), ("Morro Reatino", 0.7),
        ("Cantalupo in Sabina", 0.8), ("Casperia", 0.8),
        ("Montopoli di Sabina", 0.8), ("Salisano", 0.7),
        ("Toffia", 0.7), ("Castelnuovo di Farfa", 0.7),
        ("Mompeo", 0.7), ("Torri in Sabina", 0.7),
        ("Montebuono", 0.7), ("Collevecchio", 0.7), ("Configni", 0.7),
        ("Cottanello", 0.7), ("Vacone", 0.7),
        ("Rocca Sinibalda", 0.7), ("Longone Sabino", 0.7),
        ("Monte San Giovanni in Sabina", 0.7),
        ("Stimigliano", 0.8), ("Forano", 0.8), ("Poggio Mirteto", 0.7),
        ("Poggio Catino", 0.7), ("Poggio Nativo", 0.7),
        ("Scandriglia", 0.8), ("Orvinio", 0.7), ("Pozzaglia Sabina", 0.7),
        ("Monteflavio", 0.8), ("Nerola", 0.8), ("Sant'Angelo Romano", 0.8),
        ("Guidonia Montecelio", 0.8), ("Villanova di Guidonia", 0.8),
        ("Setteville", 0.8), ("Marco Simone", 0.8),
    ],

    # More CAMPANIA comuni
    "Campania_extra": [
        ("Cesa", 0.8), ("Frignano", 0.8), ("San Prisco", 0.8),
        ("Castel Morrone", 0.8), ("Limatola", 0.8), ("Dugenta", 0.8),
        ("Puglianello", 0.8), ("San Salvatore Telesino", 0.8),
        ("Castelvenere", 0.8), ("Torrecuso", 0.8), ("Ponte", 0.8),
        ("Paupisi", 0.8), ("Sant'Agata de' Goti", 0.8),
        ("Durazzano", 0.8), ("Moiano", 0.8), ("Bucciano", 0.8),
        ("Forchia", 0.8), ("Arpaia", 0.8), ("Paolisi", 0.8),
        ("Rotondi", 0.8), ("Cervinara", 0.8), ("San Martino Valle Caudina", 0.8),
        ("Pannarano", 0.8), ("Pietrelcina", 0.8), ("Pago Veiano", 0.8),
        ("Apice", 0.8), ("Paduli", 0.8), ("Sant'Arcangelo Trimonte", 0.8),
        ("Calvi", 0.8), ("Maddaloni", 0.8), ("Valle di Maddaloni", 0.8),
        ("San Felice a Cancello", 0.8), ("Arienzo", 0.8),
        ("Santa Maria a Vico", 0.8), ("San Nicola la Strada", 0.8),
        ("Recale", 0.8), ("Capodrise", 0.8), ("Portico di Caserta", 0.8),
        ("Macerata Campania", 0.8), ("San Tammaro", 0.8),
        ("Vitulazio", 0.8), ("Bellona", 0.8), ("Camigliano", 0.8),
        ("Sparanise", 0.8), ("Calvi Risorta", 0.8), ("Pignataro Maggiore", 0.8),
        ("Pastorano", 0.8), ("Giano Vetusto", 0.8),
        ("Caianello", 0.8), ("Pietramelara", 0.8), ("Riardo", 0.8),
        ("Rocchetta e Croce", 0.8), ("Roccaromana", 0.8),
        ("Presenzano", 0.8), ("Tora e Piccilli", 0.8),
        ("Marzano Appio", 0.8), ("Conca della Campania", 0.8),
        ("Galluccio", 0.8), ("Teano", 0.8), ("Carinola", 0.8),
    ],

    # More PUGLIA comuni
    "Puglia_extra": [
        ("Mola di Bari", 0.8), ("Noicattaro", 0.8), ("Rutigliano", 0.8),
        ("Cellamare", 0.8), ("Capurso", 0.8), ("Valenzano", 0.8),
        ("Loseto", 0.8), ("Carbonara di Bari", 0.8),
        ("Toritto", 0.8), ("Grumo Appula", 0.8), ("Binetto", 0.8),
        ("Bitetto", 0.8), ("Sannicandro di Bari", 0.8),
        ("Poggiorsini", 0.8), ("Palazzo San Gervasio", 0.8),
        ("Zapponeta", 0.8), ("Ordona", 0.8), ("Deliceto", 0.8),
        ("Sant'Agata di Puglia", 0.8), ("Accadia", 0.8),
        ("Anzano di Puglia", 0.8), ("Monteleone di Puglia", 0.8),
        ("Panni", 0.8), ("Orsara di Puglia", 0.8), ("Castelluccio Valmaggiore", 0.8),
        ("Celle di San Vito", 0.8), ("Faeto", 0.8), ("Roseto Valfortore", 0.8),
        ("Pietramontecorvino", 0.8), ("Motta Montecorvino", 0.8),
        ("Volturara Appula", 0.8), ("Volturino", 0.8), ("Biccari", 0.8),
        ("Alberona", 0.8), ("Casalnuovo Monterotaro", 0.8),
        ("Casalvecchio di Puglia", 0.8), ("Castelnuovo della Daunia", 0.8),
        ("Celenza Valfortore", 0.8), ("Carlantino", 0.8),
        ("San Marco la Catola", 0.8), ("Chieuti", 0.8), ("Serracapriola", 0.8),
        ("Lesina", 0.8), ("Poggio Imperiale", 0.8), ("Ischitella", 0.8),
        ("Rodi Garganico", 0.8), ("Vico del Gargano", 0.8),
        ("Carpino", 0.8), ("Cagnano Varano", 0.8), ("Peschici", 0.7),
        ("Tremiti", 0.7),
    ],

    # More SICILIA comuni
    "Sicilia_extra": [
        ("Aci Bonaccorsi", 0.8), ("Milo", 0.8), ("Santa Maria di Licodia", 0.8),
        ("Ragalna", 0.8), ("Camporotondo Etneo", 0.8),
        ("San Pietro Clarenza", 0.8), ("Motta Sant'Anastasia", 0.8),
        ("Belpasso", 0.8), ("Centuripe", 0.8), ("Catenanuova", 0.8),
        ("Regalbuto", 0.8), ("Troina", 0.8), ("Cerami", 0.8),
        ("Gagliano Castelferrato", 0.8), ("Sperlinga", 0.8),
        ("Assoro", 0.8), ("Valguarnera Caropepe", 0.8),
        ("Aidone", 0.8), ("Pietraperzia", 0.8), ("Nissoria", 0.8),
        ("Villarosa", 0.8), ("Santa Caterina Villarmosa", 0.8),
        ("Resuttano", 0.8), ("Villalba", 0.8), ("Marianopoli", 0.8),
        ("Mussomeli", 0.8), ("Sutera", 0.8), ("Milena", 0.8),
        ("Bompensiere", 0.8), ("Montedoro", 0.8), ("Serradifalco", 0.8),
        ("San Cataldo", 0.8), ("Delia", 0.8), ("Sommatino", 0.8),
        ("Riesi", 0.8), ("Butera", 0.8), ("Mazzarino", 0.8),
        ("Barrafranca", 0.8), ("Vallelunga Pratameno", 0.8),
        ("Campofranco", 0.8), ("Acquaviva Platani", 0.8),
        ("San Biagio Platani", 0.8), ("Alessandria della Rocca", 0.8),
        ("Bivona", 0.8), ("Santo Stefano Quisquina", 0.8),
        ("Cianciana", 0.8), ("Cattolica Eraclea", 0.8),
        ("Montallegro", 0.8), ("Siculiana", 0.8), ("Joppolo Giancaxio", 0.8),
    ],

    # More SARDEGNA comuni
    "Sardegna_extra": [
        ("Decimoputzu", 0.5), ("Villasor", 0.5), ("Siliqua", 0.5),
        ("Vallermosa", 0.5), ("Villaspeciosa", 0.5), ("Nuraminis", 0.5),
        ("Samatzai", 0.5), ("Guasila", 0.5), ("Gesico", 0.5),
        ("Mandas", 0.6), ("Isili", 0.6), ("Nurallao", 0.6),
        ("Orroli", 0.6), ("Sadali", 0.6), ("Seui", 0.6),
        ("Esterzili", 0.6), ("Escalaplano", 0.6), ("Perdasdefogu", 0.6),
        ("Ulassai", 0.6), ("Gairo", 0.6), ("Osini", 0.6),
        ("Talana", 0.5), ("Urzulei", 0.5), ("Triei", 0.6),
        ("Barisardo", 0.6), ("Cardedu", 0.6), ("Tertenia", 0.6),
        ("Villagrande Strisaili", 0.6), ("Arzana", 0.6), ("Elini", 0.6),
        ("Ilbono", 0.6), ("Loceri", 0.6), ("Lanusei", 0.6),
        ("Bonnanaro", 0.6), ("Torralba", 0.6), ("Giave", 0.6),
        ("Cossoine", 0.6), ("Cheremule", 0.6), ("Silanus", 0.6),
        ("Lei", 0.6), ("Borore", 0.6), ("Dualchi", 0.6),
        ("Noragugume", 0.6), ("Birori", 0.6), ("Bortigali", 0.6),
        ("Bolotana", 0.6), ("Orotelli", 0.6), ("Ottana", 0.6),
        ("Sarule", 0.6), ("Orani", 0.6), ("Oniferi", 0.6),
        ("Bitti", 0.6), ("Orune", 0.6), ("Lula", 0.6),
        ("Loculi", 0.6), ("Irgoli", 0.6), ("Galtellì", 0.6),
        ("Onifai", 0.6), ("Posada", 0.6), ("Torpè", 0.6),
        ("Lodè", 0.6),
    ],

    # More CALABRIA comuni
    "Calabria_extra": [
        ("San Demetrio Corone", 0.8), ("Santa Sofia d'Epiro", 0.8),
        ("San Cosmo Albanese", 0.8), ("Vaccarizzo Albanese", 0.8),
        ("San Giorgio Albanese", 0.8), ("San Benedetto Ullano", 0.8),
        ("Mongrassano", 0.8), ("Cervicati", 0.8), ("Fagnano Castello", 0.8),
        ("Cerzeto", 0.8), ("Luzzi", 0.8), ("Rose", 0.8),
        ("Zumpano", 0.8), ("San Pietro in Guarano", 0.8),
        ("Castiglione Cosentino", 0.8), ("Lappano", 0.8),
        ("Rovito", 0.8), ("Celico", 0.8), ("Spezzano della Sila", 0.8),
        ("Pedace", 0.8), ("Serra Pedace", 0.8), ("Trenta", 0.8),
        ("Mangone", 0.8), ("Figline Vegliaturo", 0.8),
        ("Aprigliano", 0.8), ("Pietrafitta", 0.8), ("Rogliano", 0.8),
        ("Marzi", 0.8), ("Grimaldi", 0.8), ("Malito", 0.8),
        ("Belsito", 0.8), ("Altilia", 0.8), ("Scigliano", 0.8),
        ("Carpanzano", 0.8), ("Pedivigliano", 0.8), ("Colosimi", 0.8),
        ("Panettieri", 0.8), ("Soveria Mannelli", 0.8),
        ("Decollatura", 0.8), ("Conflenti", 0.8), ("Motta Santa Lucia", 0.8),
        ("Martirano", 0.8), ("Martirano Lombardo", 0.8),
        ("San Mango d'Aquino", 0.8), ("Nocera Terinese", 0.8),
        ("Falerna", 0.8), ("Gizzeria", 0.8), ("Sambiase", 0.8),
        ("Nicastro", 0.8), ("Curinga", 0.8), ("Maida", 0.8),
    ],

    # More LIGURIA comuni
    "Liguria_extra": [
        ("Beverino", 0.8), ("Follo", 0.8), ("Calice al Cornoviglio", 0.8),
        ("Carro", 0.8), ("Maissana", 0.8), ("Varese Ligure", 0.8),
        ("Sesta Godano", 0.8), ("Zignago", 0.8), ("Rocchetta di Vara", 0.8),
        ("Riccò del Golfo di Spezia", 0.8), ("Portovenere", 0.8),
        ("Riomaggiore", 0.8), ("Vernazza", 0.8), ("Monterosso al Mare", 0.8),
        ("Luni", 0.8), ("Castelnuovo Magra", 0.8), ("Ortonovo", 0.8),
    ],

    # More MARCHE comuni
    "Marche_extra": [
        ("Montecassiano", 0.8), ("Montelupone", 0.8), ("Morrovalle", 0.8),
        ("Appignano", 0.8), ("Monte San Giusto", 0.8),
        ("Sant'Elpidio a Mare", 0.8), ("Montegranaro", 0.8),
        ("Rapagnano", 0.8), ("Magliano di Tenna", 0.8),
        ("Monte Giberto", 0.8), ("Ponzano di Fermo", 0.8),
        ("Belmonte Piceno", 0.8), ("Monsampietro Morico", 0.8),
        ("Monteleone di Fermo", 0.8), ("Monte Vidon Combatte", 0.8),
        ("Servigliano", 0.8), ("Santa Vittoria in Matenano", 0.8),
        ("Montelparo", 0.8), ("Montefalcone Appennino", 0.8),
        ("Smerillo", 0.8), ("Falerone", 0.8), ("Massa Fermana", 0.8),
        ("Montappone", 0.8), ("Monte Vidon Corrado", 0.8),
    ],

    # More ABRUZZO comuni
    "Abruzzo_extra": [
        ("Scurcola Marsicana", 0.8), ("Cappelle dei Marsi", 0.8),
        ("Massa d'Albe", 0.8), ("Aielli", 0.8), ("Cerchio", 0.8),
        ("Collarmele", 0.8), ("Pescina", 0.8), ("San Benedetto dei Marsi", 0.8),
        ("Gioia dei Marsi", 0.8), ("Lecce nei Marsi", 0.8),
        ("Ortucchio", 0.8), ("Villavallelonga", 0.8), ("Collelongo", 0.8),
        ("Civitella Roveto", 0.8), ("Balsorano", 0.8), ("San Vincenzo Valle Roveto", 0.8),
        ("Morino", 0.8), ("Civita d'Antino", 0.8), ("Canistro", 0.8),
        ("Luco dei Marsi", 0.8), ("Avezzano", 0.8),
    ],

    # More UMBRIA comuni
    "Umbria_extra": [
        ("Bettona", 0.8), ("Cannara", 0.8), ("Torgiano", 0.8),
        ("Brufa", 0.8), ("Passaggio di Bettona", 0.8),
        ("Costano", 0.8), ("Rivotorto", 0.8), ("Santa Maria degli Angeli", 0.8),
        ("Viole", 0.8), ("Bastardo", 0.8), ("Castel Ritaldi", 0.8),
        ("Montefalco", 0.8), ("Giano dell'Umbria", 0.8),
        ("San Terenziano", 0.8), ("Castel Ritaldi", 0.8),
    ],
}


def main():
    """Main function to load all comuni into the database."""
    db = get_db()
    cursor = db.cursor()

    # Count existing regionale entries (we will NOT touch them)
    reg_count = cursor.execute(
        "SELECT COUNT(*) FROM addizionali_irpef WHERE tipo='regionale'"
    ).fetchone()[0]
    print(f"Voci 'regionale' esistenti (non toccate): {reg_count}")

    # Delete all existing comunale entries
    cursor.execute("DELETE FROM addizionali_irpef WHERE tipo='comunale'")
    deleted = cursor.rowcount
    print(f"Eliminate {deleted} voci 'comunale' esistenti")

    # Merge "_extra" regions into main regions
    merged = {}
    for key, comuni_list in COMUNI_PER_REGIONE.items():
        # Strip "_extra" suffix to get real region name
        base_region = key.replace("_extra", "")
        if base_region not in merged:
            merged[base_region] = []
        merged[base_region].extend(comuni_list)

    # Deduplicate within each region (keep first occurrence)
    for region in merged:
        seen = set()
        unique = []
        for nome, aliquota in merged[region]:
            if nome not in seen:
                seen.add(nome)
                unique.append((nome, aliquota))
        merged[region] = unique

    # Insert all comuni
    total = 0
    summary = {}

    for regione, comuni_list in sorted(merged.items()):
        count = 0
        for nome, aliquota in comuni_list:
            cursor.execute(
                """INSERT INTO addizionali_irpef
                   (tipo, nome, regione, reddito_da, reddito_a, aliquota, anno)
                   VALUES (?, ?, ?, ?, ?, ?, ?)""",
                ('comunale', nome, regione, 0, 999999999, aliquota, 2025)
            )
            count += 1
        summary[regione] = count
        total += count

    db.commit()
    db.close()

    # Print summary
    print(f"\n{'='*50}")
    print(f"RIEPILOGO INSERIMENTO COMUNI")
    print(f"{'='*50}")
    for regione in sorted(summary.keys()):
        print(f"  {regione:30s} {summary[regione]:5d} comuni")
    print(f"{'='*50}")
    print(f"  {'TOTALE':30s} {total:5d} comuni")
    print(f"{'='*50}")

    # Verify regionale entries are intact
    db2 = get_db()
    reg_count_after = db2.execute(
        "SELECT COUNT(*) FROM addizionali_irpef WHERE tipo='regionale'"
    ).fetchone()[0]
    print(f"\nVoci 'regionale' dopo operazione: {reg_count_after} (invariate: {'SI' if reg_count_after == reg_count else 'NO!'})")
    db2.close()


if __name__ == '__main__':
    main()
